// Code generated by protoc-gen-go. DO NOT EDIT.
// source: app.proto

package pbuf

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SearchRequest struct {
	Terms                []string `protobuf:"bytes,1,rep,name=terms,proto3" json:"terms,omitempty"`
	Dataset              string   `protobuf:"bytes,2,opt,name=dataset,proto3" json:"dataset,omitempty"`
	Page                 string   `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	Query                string   `protobuf:"bytes,4,opt,name=query,proto3" json:"query,omitempty"`
	Detail               bool     `protobuf:"varint,5,opt,name=detail,proto3" json:"detail,omitempty"`
	Url                  bool     `protobuf:"varint,6,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{0}
}

func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (m *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(m, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetTerms() []string {
	if m != nil {
		return m.Terms
	}
	return nil
}

func (m *SearchRequest) GetDataset() string {
	if m != nil {
		return m.Dataset
	}
	return ""
}

func (m *SearchRequest) GetPage() string {
	if m != nil {
		return m.Page
	}
	return ""
}

func (m *SearchRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *SearchRequest) GetDetail() bool {
	if m != nil {
		return m.Detail
	}
	return false
}

func (m *SearchRequest) GetUrl() bool {
	if m != nil {
		return m.Url
	}
	return false
}

type SearchResponse struct {
	Results              *Result  `protobuf:"bytes,1,opt,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchResponse) Reset()         { *m = SearchResponse{} }
func (m *SearchResponse) String() string { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()    {}
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{1}
}

func (m *SearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResponse.Unmarshal(m, b)
}
func (m *SearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResponse.Marshal(b, m, deterministic)
}
func (m *SearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResponse.Merge(m, src)
}
func (m *SearchResponse) XXX_Size() int {
	return xxx_messageInfo_SearchResponse.Size(m)
}
func (m *SearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResponse proto.InternalMessageInfo

func (m *SearchResponse) GetResults() *Result {
	if m != nil {
		return m.Results
	}
	return nil
}

type MappingRequest struct {
	Terms                []string `protobuf:"bytes,1,rep,name=terms,proto3" json:"terms,omitempty"`
	Dataset              string   `protobuf:"bytes,2,opt,name=dataset,proto3" json:"dataset,omitempty"`
	Query                string   `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	Page                 string   `protobuf:"bytes,4,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MappingRequest) Reset()         { *m = MappingRequest{} }
func (m *MappingRequest) String() string { return proto.CompactTextString(m) }
func (*MappingRequest) ProtoMessage()    {}
func (*MappingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{2}
}

func (m *MappingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MappingRequest.Unmarshal(m, b)
}
func (m *MappingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MappingRequest.Marshal(b, m, deterministic)
}
func (m *MappingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MappingRequest.Merge(m, src)
}
func (m *MappingRequest) XXX_Size() int {
	return xxx_messageInfo_MappingRequest.Size(m)
}
func (m *MappingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MappingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MappingRequest proto.InternalMessageInfo

func (m *MappingRequest) GetTerms() []string {
	if m != nil {
		return m.Terms
	}
	return nil
}

func (m *MappingRequest) GetDataset() string {
	if m != nil {
		return m.Dataset
	}
	return ""
}

func (m *MappingRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *MappingRequest) GetPage() string {
	if m != nil {
		return m.Page
	}
	return ""
}

type MappingResponse struct {
	Results              *MapFilterResult `protobuf:"bytes,1,opt,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *MappingResponse) Reset()         { *m = MappingResponse{} }
func (m *MappingResponse) String() string { return proto.CompactTextString(m) }
func (*MappingResponse) ProtoMessage()    {}
func (*MappingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{3}
}

func (m *MappingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MappingResponse.Unmarshal(m, b)
}
func (m *MappingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MappingResponse.Marshal(b, m, deterministic)
}
func (m *MappingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MappingResponse.Merge(m, src)
}
func (m *MappingResponse) XXX_Size() int {
	return xxx_messageInfo_MappingResponse.Size(m)
}
func (m *MappingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MappingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MappingResponse proto.InternalMessageInfo

func (m *MappingResponse) GetResults() *MapFilterResult {
	if m != nil {
		return m.Results
	}
	return nil
}

type EntryRequest struct {
	Identifier           string   `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Dataset              string   `protobuf:"bytes,2,opt,name=dataset,proto3" json:"dataset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EntryRequest) Reset()         { *m = EntryRequest{} }
func (m *EntryRequest) String() string { return proto.CompactTextString(m) }
func (*EntryRequest) ProtoMessage()    {}
func (*EntryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{4}
}

func (m *EntryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntryRequest.Unmarshal(m, b)
}
func (m *EntryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntryRequest.Marshal(b, m, deterministic)
}
func (m *EntryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntryRequest.Merge(m, src)
}
func (m *EntryRequest) XXX_Size() int {
	return xxx_messageInfo_EntryRequest.Size(m)
}
func (m *EntryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EntryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EntryRequest proto.InternalMessageInfo

func (m *EntryRequest) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *EntryRequest) GetDataset() string {
	if m != nil {
		return m.Dataset
	}
	return ""
}

type EntryResponse struct {
	Result               *Xref    `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EntryResponse) Reset()         { *m = EntryResponse{} }
func (m *EntryResponse) String() string { return proto.CompactTextString(m) }
func (*EntryResponse) ProtoMessage()    {}
func (*EntryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{5}
}

func (m *EntryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntryResponse.Unmarshal(m, b)
}
func (m *EntryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntryResponse.Marshal(b, m, deterministic)
}
func (m *EntryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntryResponse.Merge(m, src)
}
func (m *EntryResponse) XXX_Size() int {
	return xxx_messageInfo_EntryResponse.Size(m)
}
func (m *EntryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EntryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EntryResponse proto.InternalMessageInfo

func (m *EntryResponse) GetResult() *Xref {
	if m != nil {
		return m.Result
	}
	return nil
}

type PageRequest struct {
	Identifier           string   `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Dataset              string   `protobuf:"bytes,2,opt,name=dataset,proto3" json:"dataset,omitempty"`
	Page                 int32    `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Total                int32    `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PageRequest) Reset()         { *m = PageRequest{} }
func (m *PageRequest) String() string { return proto.CompactTextString(m) }
func (*PageRequest) ProtoMessage()    {}
func (*PageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{6}
}

func (m *PageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageRequest.Unmarshal(m, b)
}
func (m *PageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageRequest.Marshal(b, m, deterministic)
}
func (m *PageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageRequest.Merge(m, src)
}
func (m *PageRequest) XXX_Size() int {
	return xxx_messageInfo_PageRequest.Size(m)
}
func (m *PageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PageRequest proto.InternalMessageInfo

func (m *PageRequest) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *PageRequest) GetDataset() string {
	if m != nil {
		return m.Dataset
	}
	return ""
}

func (m *PageRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *PageRequest) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type PageResponse struct {
	Result               *Result  `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PageResponse) Reset()         { *m = PageResponse{} }
func (m *PageResponse) String() string { return proto.CompactTextString(m) }
func (*PageResponse) ProtoMessage()    {}
func (*PageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{7}
}

func (m *PageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageResponse.Unmarshal(m, b)
}
func (m *PageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageResponse.Marshal(b, m, deterministic)
}
func (m *PageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageResponse.Merge(m, src)
}
func (m *PageResponse) XXX_Size() int {
	return xxx_messageInfo_PageResponse.Size(m)
}
func (m *PageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PageResponse proto.InternalMessageInfo

func (m *PageResponse) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

type FilterRequest struct {
	Identifier           string   `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Dataset              string   `protobuf:"bytes,2,opt,name=dataset,proto3" json:"dataset,omitempty"`
	Filters              []string `protobuf:"bytes,3,rep,name=filters,proto3" json:"filters,omitempty"`
	Page                 int32    `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FilterRequest) Reset()         { *m = FilterRequest{} }
func (m *FilterRequest) String() string { return proto.CompactTextString(m) }
func (*FilterRequest) ProtoMessage()    {}
func (*FilterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{8}
}

func (m *FilterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilterRequest.Unmarshal(m, b)
}
func (m *FilterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilterRequest.Marshal(b, m, deterministic)
}
func (m *FilterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilterRequest.Merge(m, src)
}
func (m *FilterRequest) XXX_Size() int {
	return xxx_messageInfo_FilterRequest.Size(m)
}
func (m *FilterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FilterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FilterRequest proto.InternalMessageInfo

func (m *FilterRequest) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *FilterRequest) GetDataset() string {
	if m != nil {
		return m.Dataset
	}
	return ""
}

func (m *FilterRequest) GetFilters() []string {
	if m != nil {
		return m.Filters
	}
	return nil
}

func (m *FilterRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

type FilterResponse struct {
	Result               *Result  `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FilterResponse) Reset()         { *m = FilterResponse{} }
func (m *FilterResponse) String() string { return proto.CompactTextString(m) }
func (*FilterResponse) ProtoMessage()    {}
func (*FilterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{9}
}

func (m *FilterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilterResponse.Unmarshal(m, b)
}
func (m *FilterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilterResponse.Marshal(b, m, deterministic)
}
func (m *FilterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilterResponse.Merge(m, src)
}
func (m *FilterResponse) XXX_Size() int {
	return xxx_messageInfo_FilterResponse.Size(m)
}
func (m *FilterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FilterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FilterResponse proto.InternalMessageInfo

func (m *FilterResponse) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

type MetaRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MetaRequest) Reset()         { *m = MetaRequest{} }
func (m *MetaRequest) String() string { return proto.CompactTextString(m) }
func (*MetaRequest) ProtoMessage()    {}
func (*MetaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{10}
}

func (m *MetaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetaRequest.Unmarshal(m, b)
}
func (m *MetaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetaRequest.Marshal(b, m, deterministic)
}
func (m *MetaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetaRequest.Merge(m, src)
}
func (m *MetaRequest) XXX_Size() int {
	return xxx_messageInfo_MetaRequest.Size(m)
}
func (m *MetaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MetaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MetaRequest proto.InternalMessageInfo

type MetaResponse struct {
	Results              map[string]*MetaKeyValue `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *MetaResponse) Reset()         { *m = MetaResponse{} }
func (m *MetaResponse) String() string { return proto.CompactTextString(m) }
func (*MetaResponse) ProtoMessage()    {}
func (*MetaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{11}
}

func (m *MetaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetaResponse.Unmarshal(m, b)
}
func (m *MetaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetaResponse.Marshal(b, m, deterministic)
}
func (m *MetaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetaResponse.Merge(m, src)
}
func (m *MetaResponse) XXX_Size() int {
	return xxx_messageInfo_MetaResponse.Size(m)
}
func (m *MetaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MetaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MetaResponse proto.InternalMessageInfo

func (m *MetaResponse) GetResults() map[string]*MetaKeyValue {
	if m != nil {
		return m.Results
	}
	return nil
}

type MetaKeyValue struct {
	Keyvalues            map[string]string `protobuf:"bytes,1,rep,name=keyvalues,proto3" json:"keyvalues,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *MetaKeyValue) Reset()         { *m = MetaKeyValue{} }
func (m *MetaKeyValue) String() string { return proto.CompactTextString(m) }
func (*MetaKeyValue) ProtoMessage()    {}
func (*MetaKeyValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{12}
}

func (m *MetaKeyValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetaKeyValue.Unmarshal(m, b)
}
func (m *MetaKeyValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetaKeyValue.Marshal(b, m, deterministic)
}
func (m *MetaKeyValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetaKeyValue.Merge(m, src)
}
func (m *MetaKeyValue) XXX_Size() int {
	return xxx_messageInfo_MetaKeyValue.Size(m)
}
func (m *MetaKeyValue) XXX_DiscardUnknown() {
	xxx_messageInfo_MetaKeyValue.DiscardUnknown(m)
}

var xxx_messageInfo_MetaKeyValue proto.InternalMessageInfo

func (m *MetaKeyValue) GetKeyvalues() map[string]string {
	if m != nil {
		return m.Keyvalues
	}
	return nil
}

type ListGenomesRequest struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListGenomesRequest) Reset()         { *m = ListGenomesRequest{} }
func (m *ListGenomesRequest) String() string { return proto.CompactTextString(m) }
func (*ListGenomesRequest) ProtoMessage()    {}
func (*ListGenomesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{13}
}

func (m *ListGenomesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListGenomesRequest.Unmarshal(m, b)
}
func (m *ListGenomesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListGenomesRequest.Marshal(b, m, deterministic)
}
func (m *ListGenomesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListGenomesRequest.Merge(m, src)
}
func (m *ListGenomesRequest) XXX_Size() int {
	return xxx_messageInfo_ListGenomesRequest.Size(m)
}
func (m *ListGenomesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListGenomesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListGenomesRequest proto.InternalMessageInfo

func (m *ListGenomesRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type ListGenomesResponse struct {
	Results              string   `protobuf:"bytes,1,opt,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListGenomesResponse) Reset()         { *m = ListGenomesResponse{} }
func (m *ListGenomesResponse) String() string { return proto.CompactTextString(m) }
func (*ListGenomesResponse) ProtoMessage()    {}
func (*ListGenomesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{14}
}

func (m *ListGenomesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListGenomesResponse.Unmarshal(m, b)
}
func (m *ListGenomesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListGenomesResponse.Marshal(b, m, deterministic)
}
func (m *ListGenomesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListGenomesResponse.Merge(m, src)
}
func (m *ListGenomesResponse) XXX_Size() int {
	return xxx_messageInfo_ListGenomesResponse.Size(m)
}
func (m *ListGenomesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListGenomesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListGenomesResponse proto.InternalMessageInfo

func (m *ListGenomesResponse) GetResults() string {
	if m != nil {
		return m.Results
	}
	return ""
}

type Result struct {
	Results              []*Xref  `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Nextpage             string   `protobuf:"bytes,2,opt,name=nextpage,proto3" json:"nextpage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{15}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetResults() []*Xref {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *Result) GetNextpage() string {
	if m != nil {
		return m.Nextpage
	}
	return ""
}

type MapFilterResult struct {
	Results              []*MapFilter `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Nextpage             string       `protobuf:"bytes,2,opt,name=nextpage,proto3" json:"nextpage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *MapFilterResult) Reset()         { *m = MapFilterResult{} }
func (m *MapFilterResult) String() string { return proto.CompactTextString(m) }
func (*MapFilterResult) ProtoMessage()    {}
func (*MapFilterResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{16}
}

func (m *MapFilterResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MapFilterResult.Unmarshal(m, b)
}
func (m *MapFilterResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MapFilterResult.Marshal(b, m, deterministic)
}
func (m *MapFilterResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MapFilterResult.Merge(m, src)
}
func (m *MapFilterResult) XXX_Size() int {
	return xxx_messageInfo_MapFilterResult.Size(m)
}
func (m *MapFilterResult) XXX_DiscardUnknown() {
	xxx_messageInfo_MapFilterResult.DiscardUnknown(m)
}

var xxx_messageInfo_MapFilterResult proto.InternalMessageInfo

func (m *MapFilterResult) GetResults() []*MapFilter {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *MapFilterResult) GetNextpage() string {
	if m != nil {
		return m.Nextpage
	}
	return ""
}

type MapFilter struct {
	Source               *Xref    `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Targets              []*Xref  `protobuf:"bytes,2,rep,name=targets,proto3" json:"targets,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MapFilter) Reset()         { *m = MapFilter{} }
func (m *MapFilter) String() string { return proto.CompactTextString(m) }
func (*MapFilter) ProtoMessage()    {}
func (*MapFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{17}
}

func (m *MapFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MapFilter.Unmarshal(m, b)
}
func (m *MapFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MapFilter.Marshal(b, m, deterministic)
}
func (m *MapFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MapFilter.Merge(m, src)
}
func (m *MapFilter) XXX_Size() int {
	return xxx_messageInfo_MapFilter.Size(m)
}
func (m *MapFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_MapFilter.DiscardUnknown(m)
}

var xxx_messageInfo_MapFilter proto.InternalMessageInfo

func (m *MapFilter) GetSource() *Xref {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *MapFilter) GetTargets() []*Xref {
	if m != nil {
		return m.Targets
	}
	return nil
}

type Xref struct {
	Dataset    uint32 `protobuf:"varint,1,opt,name=dataset,proto3" json:"dataset,omitempty"`
	IsLink     bool   `protobuf:"varint,2,opt,name=is_link,json=isLink,proto3" json:"is_link,omitempty"`
	Identifier string `protobuf:"bytes,3,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Keyword    string `protobuf:"bytes,4,opt,name=keyword,proto3" json:"keyword,omitempty"`
	// Types that are valid to be assigned to Attributes:
	//	*Xref_Empty
	//	*Xref_Uniprot
	//	*Xref_Ontology
	//	*Xref_Hgnc
	//	*Xref_Interpro
	//	*Xref_Ensembl
	//	*Xref_Taxonomy
	//	*Xref_Hmdb
	//	*Xref_Ena
	//	*Xref_Pdb
	//	*Xref_Drugbank
	//	*Xref_Orphanet
	//	*Xref_Reactome
	//	*Xref_Chembl
	//	*Xref_Ufeature
	Attributes           isXref_Attributes    `protobuf_oneof:"attributes"`
	Count                uint32               `protobuf:"varint,20,opt,name=count,proto3" json:"count,omitempty"`
	Entries              []*XrefEntry         `protobuf:"bytes,21,rep,name=entries,proto3" json:"entries,omitempty"`
	DatasetCounts        []*XrefDomainCount   `protobuf:"bytes,22,rep,name=dataset_counts,json=datasetCounts,proto3" json:"dataset_counts,omitempty"`
	DatasetPages         map[uint32]*PageInfo `protobuf:"bytes,23,rep,name=datasetPages,proto3" json:"datasetPages,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Pages                []string             `protobuf:"bytes,24,rep,name=pages,proto3" json:"pages,omitempty"`
	Url                  string               `protobuf:"bytes,25,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Xref) Reset()         { *m = Xref{} }
func (m *Xref) String() string { return proto.CompactTextString(m) }
func (*Xref) ProtoMessage()    {}
func (*Xref) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{18}
}

func (m *Xref) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Xref.Unmarshal(m, b)
}
func (m *Xref) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Xref.Marshal(b, m, deterministic)
}
func (m *Xref) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Xref.Merge(m, src)
}
func (m *Xref) XXX_Size() int {
	return xxx_messageInfo_Xref.Size(m)
}
func (m *Xref) XXX_DiscardUnknown() {
	xxx_messageInfo_Xref.DiscardUnknown(m)
}

var xxx_messageInfo_Xref proto.InternalMessageInfo

func (m *Xref) GetDataset() uint32 {
	if m != nil {
		return m.Dataset
	}
	return 0
}

func (m *Xref) GetIsLink() bool {
	if m != nil {
		return m.IsLink
	}
	return false
}

func (m *Xref) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *Xref) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

type isXref_Attributes interface {
	isXref_Attributes()
}

type Xref_Empty struct {
	Empty bool `protobuf:"varint,5,opt,name=empty,proto3,oneof"`
}

type Xref_Uniprot struct {
	Uniprot *UniprotAttr `protobuf:"bytes,6,opt,name=uniprot,proto3,oneof"`
}

type Xref_Ontology struct {
	Ontology *OntologyAttr `protobuf:"bytes,7,opt,name=ontology,proto3,oneof"`
}

type Xref_Hgnc struct {
	Hgnc *HgncAttr `protobuf:"bytes,8,opt,name=hgnc,proto3,oneof"`
}

type Xref_Interpro struct {
	Interpro *InterproAttr `protobuf:"bytes,9,opt,name=interpro,proto3,oneof"`
}

type Xref_Ensembl struct {
	Ensembl *EnsemblAttr `protobuf:"bytes,10,opt,name=ensembl,proto3,oneof"`
}

type Xref_Taxonomy struct {
	Taxonomy *TaxoAttr `protobuf:"bytes,11,opt,name=taxonomy,proto3,oneof"`
}

type Xref_Hmdb struct {
	Hmdb *HmdbAttr `protobuf:"bytes,12,opt,name=hmdb,proto3,oneof"`
}

type Xref_Ena struct {
	Ena *EnaAttr `protobuf:"bytes,13,opt,name=ena,proto3,oneof"`
}

type Xref_Pdb struct {
	Pdb *PdbAttr `protobuf:"bytes,14,opt,name=pdb,proto3,oneof"`
}

type Xref_Drugbank struct {
	Drugbank *DrugbankAttr `protobuf:"bytes,15,opt,name=drugbank,proto3,oneof"`
}

type Xref_Orphanet struct {
	Orphanet *OrphanetAttr `protobuf:"bytes,16,opt,name=orphanet,proto3,oneof"`
}

type Xref_Reactome struct {
	Reactome *ReactomeAttr `protobuf:"bytes,17,opt,name=reactome,proto3,oneof"`
}

type Xref_Chembl struct {
	Chembl *ChemblAttr `protobuf:"bytes,18,opt,name=chembl,proto3,oneof"`
}

type Xref_Ufeature struct {
	Ufeature *UniprotFeatureAttr `protobuf:"bytes,19,opt,name=ufeature,proto3,oneof"`
}

func (*Xref_Empty) isXref_Attributes() {}

func (*Xref_Uniprot) isXref_Attributes() {}

func (*Xref_Ontology) isXref_Attributes() {}

func (*Xref_Hgnc) isXref_Attributes() {}

func (*Xref_Interpro) isXref_Attributes() {}

func (*Xref_Ensembl) isXref_Attributes() {}

func (*Xref_Taxonomy) isXref_Attributes() {}

func (*Xref_Hmdb) isXref_Attributes() {}

func (*Xref_Ena) isXref_Attributes() {}

func (*Xref_Pdb) isXref_Attributes() {}

func (*Xref_Drugbank) isXref_Attributes() {}

func (*Xref_Orphanet) isXref_Attributes() {}

func (*Xref_Reactome) isXref_Attributes() {}

func (*Xref_Chembl) isXref_Attributes() {}

func (*Xref_Ufeature) isXref_Attributes() {}

func (m *Xref) GetAttributes() isXref_Attributes {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *Xref) GetEmpty() bool {
	if x, ok := m.GetAttributes().(*Xref_Empty); ok {
		return x.Empty
	}
	return false
}

func (m *Xref) GetUniprot() *UniprotAttr {
	if x, ok := m.GetAttributes().(*Xref_Uniprot); ok {
		return x.Uniprot
	}
	return nil
}

func (m *Xref) GetOntology() *OntologyAttr {
	if x, ok := m.GetAttributes().(*Xref_Ontology); ok {
		return x.Ontology
	}
	return nil
}

func (m *Xref) GetHgnc() *HgncAttr {
	if x, ok := m.GetAttributes().(*Xref_Hgnc); ok {
		return x.Hgnc
	}
	return nil
}

func (m *Xref) GetInterpro() *InterproAttr {
	if x, ok := m.GetAttributes().(*Xref_Interpro); ok {
		return x.Interpro
	}
	return nil
}

func (m *Xref) GetEnsembl() *EnsemblAttr {
	if x, ok := m.GetAttributes().(*Xref_Ensembl); ok {
		return x.Ensembl
	}
	return nil
}

func (m *Xref) GetTaxonomy() *TaxoAttr {
	if x, ok := m.GetAttributes().(*Xref_Taxonomy); ok {
		return x.Taxonomy
	}
	return nil
}

func (m *Xref) GetHmdb() *HmdbAttr {
	if x, ok := m.GetAttributes().(*Xref_Hmdb); ok {
		return x.Hmdb
	}
	return nil
}

func (m *Xref) GetEna() *EnaAttr {
	if x, ok := m.GetAttributes().(*Xref_Ena); ok {
		return x.Ena
	}
	return nil
}

func (m *Xref) GetPdb() *PdbAttr {
	if x, ok := m.GetAttributes().(*Xref_Pdb); ok {
		return x.Pdb
	}
	return nil
}

func (m *Xref) GetDrugbank() *DrugbankAttr {
	if x, ok := m.GetAttributes().(*Xref_Drugbank); ok {
		return x.Drugbank
	}
	return nil
}

func (m *Xref) GetOrphanet() *OrphanetAttr {
	if x, ok := m.GetAttributes().(*Xref_Orphanet); ok {
		return x.Orphanet
	}
	return nil
}

func (m *Xref) GetReactome() *ReactomeAttr {
	if x, ok := m.GetAttributes().(*Xref_Reactome); ok {
		return x.Reactome
	}
	return nil
}

func (m *Xref) GetChembl() *ChemblAttr {
	if x, ok := m.GetAttributes().(*Xref_Chembl); ok {
		return x.Chembl
	}
	return nil
}

func (m *Xref) GetUfeature() *UniprotFeatureAttr {
	if x, ok := m.GetAttributes().(*Xref_Ufeature); ok {
		return x.Ufeature
	}
	return nil
}

func (m *Xref) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *Xref) GetEntries() []*XrefEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

func (m *Xref) GetDatasetCounts() []*XrefDomainCount {
	if m != nil {
		return m.DatasetCounts
	}
	return nil
}

func (m *Xref) GetDatasetPages() map[uint32]*PageInfo {
	if m != nil {
		return m.DatasetPages
	}
	return nil
}

func (m *Xref) GetPages() []string {
	if m != nil {
		return m.Pages
	}
	return nil
}

func (m *Xref) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Xref) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Xref_Empty)(nil),
		(*Xref_Uniprot)(nil),
		(*Xref_Ontology)(nil),
		(*Xref_Hgnc)(nil),
		(*Xref_Interpro)(nil),
		(*Xref_Ensembl)(nil),
		(*Xref_Taxonomy)(nil),
		(*Xref_Hmdb)(nil),
		(*Xref_Ena)(nil),
		(*Xref_Pdb)(nil),
		(*Xref_Drugbank)(nil),
		(*Xref_Orphanet)(nil),
		(*Xref_Reactome)(nil),
		(*Xref_Chembl)(nil),
		(*Xref_Ufeature)(nil),
	}
}

type PageInfo struct {
	Pages                []string `protobuf:"bytes,1,rep,name=pages,proto3" json:"pages,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PageInfo) Reset()         { *m = PageInfo{} }
func (m *PageInfo) String() string { return proto.CompactTextString(m) }
func (*PageInfo) ProtoMessage()    {}
func (*PageInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{19}
}

func (m *PageInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageInfo.Unmarshal(m, b)
}
func (m *PageInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageInfo.Marshal(b, m, deterministic)
}
func (m *PageInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageInfo.Merge(m, src)
}
func (m *PageInfo) XXX_Size() int {
	return xxx_messageInfo_PageInfo.Size(m)
}
func (m *PageInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PageInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PageInfo proto.InternalMessageInfo

func (m *PageInfo) GetPages() []string {
	if m != nil {
		return m.Pages
	}
	return nil
}

type XrefEntry struct {
	Dataset              uint32   `protobuf:"varint,1,opt,name=dataset,proto3" json:"dataset,omitempty"`
	Identifier           string   `protobuf:"bytes,2,opt,name=identifier,proto3" json:"identifier,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *XrefEntry) Reset()         { *m = XrefEntry{} }
func (m *XrefEntry) String() string { return proto.CompactTextString(m) }
func (*XrefEntry) ProtoMessage()    {}
func (*XrefEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{20}
}

func (m *XrefEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XrefEntry.Unmarshal(m, b)
}
func (m *XrefEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XrefEntry.Marshal(b, m, deterministic)
}
func (m *XrefEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XrefEntry.Merge(m, src)
}
func (m *XrefEntry) XXX_Size() int {
	return xxx_messageInfo_XrefEntry.Size(m)
}
func (m *XrefEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_XrefEntry.DiscardUnknown(m)
}

var xxx_messageInfo_XrefEntry proto.InternalMessageInfo

func (m *XrefEntry) GetDataset() uint32 {
	if m != nil {
		return m.Dataset
	}
	return 0
}

func (m *XrefEntry) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

type XrefDomainCount struct {
	Dataset              uint32   `protobuf:"varint,1,opt,name=dataset,proto3" json:"dataset,omitempty"`
	Count                uint32   `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *XrefDomainCount) Reset()         { *m = XrefDomainCount{} }
func (m *XrefDomainCount) String() string { return proto.CompactTextString(m) }
func (*XrefDomainCount) ProtoMessage()    {}
func (*XrefDomainCount) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{21}
}

func (m *XrefDomainCount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XrefDomainCount.Unmarshal(m, b)
}
func (m *XrefDomainCount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XrefDomainCount.Marshal(b, m, deterministic)
}
func (m *XrefDomainCount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XrefDomainCount.Merge(m, src)
}
func (m *XrefDomainCount) XXX_Size() int {
	return xxx_messageInfo_XrefDomainCount.Size(m)
}
func (m *XrefDomainCount) XXX_DiscardUnknown() {
	xxx_messageInfo_XrefDomainCount.DiscardUnknown(m)
}

var xxx_messageInfo_XrefDomainCount proto.InternalMessageInfo

func (m *XrefDomainCount) GetDataset() uint32 {
	if m != nil {
		return m.Dataset
	}
	return 0
}

func (m *XrefDomainCount) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type Alias struct {
	Identifiers          []string `protobuf:"bytes,1,rep,name=identifiers,proto3" json:"identifiers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Alias) Reset()         { *m = Alias{} }
func (m *Alias) String() string { return proto.CompactTextString(m) }
func (*Alias) ProtoMessage()    {}
func (*Alias) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{22}
}

func (m *Alias) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Alias.Unmarshal(m, b)
}
func (m *Alias) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Alias.Marshal(b, m, deterministic)
}
func (m *Alias) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Alias.Merge(m, src)
}
func (m *Alias) XXX_Size() int {
	return xxx_messageInfo_Alias.Size(m)
}
func (m *Alias) XXX_DiscardUnknown() {
	xxx_messageInfo_Alias.DiscardUnknown(m)
}

var xxx_messageInfo_Alias proto.InternalMessageInfo

func (m *Alias) GetIdentifiers() []string {
	if m != nil {
		return m.Identifiers
	}
	return nil
}

func init() {
	proto.RegisterType((*SearchRequest)(nil), "pbuf.SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "pbuf.SearchResponse")
	proto.RegisterType((*MappingRequest)(nil), "pbuf.MappingRequest")
	proto.RegisterType((*MappingResponse)(nil), "pbuf.MappingResponse")
	proto.RegisterType((*EntryRequest)(nil), "pbuf.EntryRequest")
	proto.RegisterType((*EntryResponse)(nil), "pbuf.EntryResponse")
	proto.RegisterType((*PageRequest)(nil), "pbuf.PageRequest")
	proto.RegisterType((*PageResponse)(nil), "pbuf.PageResponse")
	proto.RegisterType((*FilterRequest)(nil), "pbuf.FilterRequest")
	proto.RegisterType((*FilterResponse)(nil), "pbuf.FilterResponse")
	proto.RegisterType((*MetaRequest)(nil), "pbuf.MetaRequest")
	proto.RegisterType((*MetaResponse)(nil), "pbuf.MetaResponse")
	proto.RegisterMapType((map[string]*MetaKeyValue)(nil), "pbuf.MetaResponse.ResultsEntry")
	proto.RegisterType((*MetaKeyValue)(nil), "pbuf.MetaKeyValue")
	proto.RegisterMapType((map[string]string)(nil), "pbuf.MetaKeyValue.KeyvaluesEntry")
	proto.RegisterType((*ListGenomesRequest)(nil), "pbuf.ListGenomesRequest")
	proto.RegisterType((*ListGenomesResponse)(nil), "pbuf.ListGenomesResponse")
	proto.RegisterType((*Result)(nil), "pbuf.Result")
	proto.RegisterType((*MapFilterResult)(nil), "pbuf.MapFilterResult")
	proto.RegisterType((*MapFilter)(nil), "pbuf.MapFilter")
	proto.RegisterType((*Xref)(nil), "pbuf.Xref")
	proto.RegisterMapType((map[uint32]*PageInfo)(nil), "pbuf.Xref.DatasetPagesEntry")
	proto.RegisterType((*PageInfo)(nil), "pbuf.PageInfo")
	proto.RegisterType((*XrefEntry)(nil), "pbuf.XrefEntry")
	proto.RegisterType((*XrefDomainCount)(nil), "pbuf.XrefDomainCount")
	proto.RegisterType((*Alias)(nil), "pbuf.Alias")
}

func init() { proto.RegisterFile("app.proto", fileDescriptor_e0f9056a14b86d47) }

var fileDescriptor_e0f9056a14b86d47 = []byte{
	// 1214 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x57, 0xdb, 0x6e, 0xdb, 0x46,
	0x13, 0x8e, 0xac, 0xf3, 0xe8, 0xe0, 0x78, 0x7d, 0xc8, 0x46, 0xf8, 0xf1, 0xd7, 0x21, 0x8c, 0x42,
	0x29, 0x6a, 0x27, 0xb0, 0x0b, 0x23, 0x2d, 0x02, 0xb4, 0x76, 0xec, 0xd4, 0x69, 0xe2, 0x26, 0x60,
	0x9a, 0x22, 0x77, 0xc1, 0x4a, 0x1a, 0xc9, 0xac, 0x24, 0x92, 0x5e, 0x2e, 0x13, 0xeb, 0x09, 0x7a,
	0xd5, 0xab, 0x5e, 0xf5, 0xa9, 0xfa, 0x4a, 0xc5, 0x9e, 0xc8, 0xa5, 0xec, 0x06, 0x6d, 0x73, 0xc7,
	0x99, 0xf9, 0x66, 0xf6, 0xdb, 0x9d, 0x9d, 0xd9, 0x21, 0x34, 0x59, 0x1c, 0xef, 0xc5, 0x3c, 0x12,
	0x11, 0xa9, 0xc4, 0x83, 0x74, 0xdc, 0x03, 0x26, 0x04, 0xd7, 0x1a, 0xef, 0xf7, 0x12, 0x74, 0x5e,
	0x23, 0xe3, 0xc3, 0x0b, 0x1f, 0x2f, 0x53, 0x4c, 0x04, 0xd9, 0x80, 0xaa, 0x40, 0x3e, 0x4f, 0x68,
	0x69, 0xbb, 0xdc, 0x6f, 0xfa, 0x5a, 0x20, 0x14, 0xea, 0x23, 0x26, 0x58, 0x82, 0x82, 0xae, 0x6c,
	0x97, 0xfa, 0x4d, 0xdf, 0x8a, 0x84, 0x40, 0x25, 0x66, 0x13, 0xa4, 0x65, 0xa5, 0x56, 0xdf, 0x32,
	0xc6, 0x65, 0x8a, 0x7c, 0x41, 0x2b, 0x4a, 0xa9, 0x05, 0xb2, 0x05, 0xb5, 0x11, 0x0a, 0x16, 0xcc,
	0x68, 0x75, 0xbb, 0xd4, 0x6f, 0xf8, 0x46, 0x22, 0xb7, 0xa1, 0x9c, 0xf2, 0x19, 0xad, 0x29, 0xa5,
	0xfc, 0xf4, 0x1e, 0x41, 0xd7, 0x92, 0x4a, 0xe2, 0x28, 0x4c, 0x90, 0x7c, 0x0e, 0x75, 0x8e, 0x49,
	0x3a, 0x13, 0x92, 0x57, 0xa9, 0xdf, 0xda, 0x6f, 0xef, 0xc9, 0xbd, 0xec, 0xf9, 0x4a, 0xe9, 0x5b,
	0xa3, 0xf7, 0x0b, 0x74, 0xcf, 0x59, 0x1c, 0x07, 0xe1, 0xe4, 0xbf, 0xee, 0x27, 0xe3, 0x5e, 0x76,
	0xb9, 0xdb, 0x5d, 0x56, 0xf2, 0x5d, 0x7a, 0xc7, 0xb0, 0x9a, 0xad, 0x65, 0x68, 0x3e, 0x58, 0xa6,
	0xb9, 0xa9, 0x69, 0x9e, 0xb3, 0xf8, 0x69, 0x30, 0x13, 0xc8, 0x97, 0xf9, 0x9e, 0x41, 0xfb, 0x34,
	0x14, 0x7c, 0x61, 0xd9, 0xfe, 0x1f, 0x20, 0x18, 0x61, 0x28, 0x82, 0x71, 0x80, 0x5c, 0xc5, 0x68,
	0xfa, 0x8e, 0xe6, 0xef, 0x79, 0x7b, 0x07, 0xd0, 0x31, 0x91, 0x0c, 0x17, 0x0f, 0x6a, 0x7a, 0x15,
	0x43, 0x05, 0x34, 0x95, 0xb7, 0x1c, 0xc7, 0xbe, 0xb1, 0x78, 0x97, 0xd0, 0x7a, 0xc5, 0x26, 0xf8,
	0xc9, 0xab, 0x17, 0x6e, 0x41, 0x35, 0xbf, 0x05, 0x22, 0x12, 0x6c, 0xa6, 0x0e, 0xad, 0xea, 0x6b,
	0xc1, 0xfb, 0x0a, 0xda, 0x7a, 0x49, 0x43, 0x73, 0x67, 0x89, 0x66, 0x31, 0xb1, 0x96, 0xe8, 0x07,
	0xe8, 0xd8, 0x03, 0xfc, 0x54, 0xaa, 0x14, 0xea, 0x63, 0x15, 0x2a, 0xa1, 0x65, 0x75, 0x25, 0xac,
	0x58, 0x48, 0xb2, 0xd9, 0x84, 0x77, 0x08, 0xdd, 0x2c, 0x73, 0xff, 0x86, 0x70, 0x07, 0x5a, 0xe7,
	0x28, 0x98, 0xa1, 0xeb, 0xfd, 0x51, 0x82, 0xb6, 0x96, 0x4d, 0x94, 0xaf, 0xdd, 0x9b, 0x52, 0xee,
	0xb7, 0xf6, 0x3f, 0x33, 0x37, 0xc5, 0x01, 0x99, 0x98, 0x89, 0xce, 0xab, 0xc5, 0xf7, 0x7e, 0x84,
	0xb6, 0x6b, 0x90, 0xf5, 0x33, 0xc5, 0x85, 0x39, 0x03, 0xf9, 0x49, 0xfa, 0x50, 0x7d, 0xcf, 0x66,
	0x29, 0xaa, 0xad, 0xb7, 0xf6, 0x49, 0x1e, 0xfa, 0x39, 0x2e, 0x7e, 0x96, 0x16, 0x5f, 0x03, 0xbe,
	0x59, 0x79, 0x54, 0xf2, 0x7e, 0x33, 0xdc, 0xac, 0x8d, 0x7c, 0x0b, 0xcd, 0x29, 0x2e, 0x14, 0xc0,
	0xb2, 0xbb, 0x77, 0x3d, 0xc4, 0xde, 0x73, 0x8b, 0xd1, 0xfc, 0x72, 0x9f, 0xde, 0x63, 0xe8, 0x16,
	0x8d, 0x37, 0x70, 0xdc, 0x70, 0x39, 0x36, 0x5d, 0x3e, 0x7d, 0x20, 0x2f, 0x82, 0x44, 0x7c, 0x8f,
	0x61, 0x34, 0xc7, 0xc4, 0x26, 0x9c, 0x40, 0x45, 0x2c, 0x62, 0x34, 0x21, 0xd4, 0xb7, 0xf7, 0x00,
	0xd6, 0x0b, 0x48, 0x73, 0xb6, 0xb4, 0x58, 0x85, 0xcd, 0xbc, 0xdc, 0x7e, 0x80, 0x9a, 0x3e, 0x3a,
	0xb2, 0xb3, 0x7c, 0xfe, 0x6e, 0x79, 0x58, 0x13, 0xe9, 0x41, 0x23, 0xc4, 0x2b, 0xa1, 0x6e, 0x85,
	0xe6, 0x99, 0xc9, 0xde, 0x5b, 0x55, 0xfe, 0x6e, 0x59, 0x93, 0xfb, 0xcb, 0x41, 0x57, 0x97, 0xcb,
	0xff, 0x1f, 0x45, 0x7e, 0x03, 0xcd, 0xcc, 0x43, 0x96, 0x71, 0x12, 0xa5, 0x7c, 0x88, 0x37, 0x95,
	0xb1, 0xb6, 0xc8, 0xcd, 0x08, 0xc6, 0x27, 0x28, 0x12, 0xba, 0x72, 0x7d, 0x33, 0xc6, 0xe4, 0xfd,
	0xd9, 0x80, 0x8a, 0xd4, 0xb8, 0xb5, 0x21, 0x63, 0x76, 0xf2, 0xda, 0xb8, 0x03, 0xf5, 0x20, 0x79,
	0x37, 0x0b, 0xc2, 0xa9, 0x22, 0xd5, 0xf0, 0x6b, 0x41, 0xf2, 0x22, 0x08, 0xa7, 0x4b, 0xe5, 0x56,
	0xbe, 0xa9, 0xdc, 0xa6, 0xb8, 0xf8, 0x10, 0xf1, 0x91, 0x69, 0x91, 0x56, 0x24, 0x5b, 0x50, 0xc5,
	0x79, 0x2c, 0x16, 0xba, 0xe9, 0x9f, 0xdd, 0xf2, 0xb5, 0x48, 0x76, 0xa1, 0x9e, 0x86, 0x81, 0x7c,
	0x85, 0x54, 0xe7, 0x6f, 0xed, 0xaf, 0x69, 0xce, 0x6f, 0xb4, 0xf2, 0x48, 0x08, 0x7e, 0x76, 0xcb,
	0xb7, 0x18, 0xf2, 0x10, 0x1a, 0x51, 0x28, 0xa2, 0x59, 0x34, 0x59, 0xd0, 0xba, 0x7b, 0xab, 0x5f,
	0x1a, 0xad, 0x71, 0xc8, 0x50, 0x64, 0x07, 0x2a, 0x17, 0x93, 0x70, 0x48, 0x1b, 0x0a, 0xdd, 0xd5,
	0xe8, 0xb3, 0x49, 0x38, 0x34, 0x48, 0x65, 0x95, 0x71, 0x83, 0x50, 0x20, 0x8f, 0x79, 0x44, 0x9b,
	0x6e, 0xdc, 0x67, 0x46, 0x6b, 0xe3, 0x5a, 0x94, 0x24, 0x8e, 0x61, 0x82, 0xf3, 0xc1, 0x8c, 0x82,
	0x4b, 0xfc, 0x54, 0x2b, 0x2d, 0x71, 0x83, 0x21, 0x5f, 0x42, 0x43, 0xb0, 0xab, 0x28, 0x8c, 0xe6,
	0x0b, 0xda, 0x72, 0xa9, 0xfc, 0xc4, 0xae, 0xb2, 0xe0, 0x16, 0xa1, 0x48, 0xcf, 0x47, 0x03, 0xda,
	0x2e, 0x90, 0x9e, 0x8f, 0x06, 0x19, 0xe9, 0xf9, 0x68, 0x40, 0xee, 0x41, 0x19, 0x43, 0x46, 0x3b,
	0x0a, 0xd4, 0xb1, 0xcb, 0x33, 0x83, 0x91, 0x36, 0x09, 0x89, 0x47, 0x03, 0xda, 0x75, 0x21, 0xaf,
	0xb2, 0x30, 0xd2, 0x26, 0xb7, 0x3e, 0xe2, 0xe9, 0x64, 0xc0, 0xc2, 0x29, 0x5d, 0x75, 0xb7, 0x7e,
	0x62, 0xb4, 0x96, 0x9d, 0x45, 0xa9, 0x24, 0xf0, 0xf8, 0x82, 0x85, 0x28, 0xe8, 0xed, 0x42, 0x12,
	0x8c, 0x36, 0x4b, 0x82, 0x91, 0xa5, 0x07, 0x47, 0x36, 0x14, 0xd1, 0x1c, 0xe9, 0x9a, 0xeb, 0xe1,
	0x1b, 0xad, 0xf5, 0xb0, 0x28, 0xf2, 0x05, 0xd4, 0x86, 0x17, 0xea, 0x74, 0x89, 0xc2, 0xdf, 0xd6,
	0xf8, 0x27, 0x17, 0xce, 0xe1, 0x1a, 0x04, 0x39, 0x84, 0x46, 0x3a, 0x46, 0x26, 0x52, 0x8e, 0x74,
	0x5d, 0xa1, 0x69, 0xe1, 0x12, 0x3d, 0xd5, 0x36, 0xbb, 0x86, 0xc5, 0xca, 0xde, 0x33, 0x8c, 0xd2,
	0x50, 0xd0, 0x0d, 0x75, 0xfd, 0xb5, 0x20, 0xab, 0x17, 0x43, 0xc1, 0x03, 0x4c, 0xe8, 0xa6, 0x5b,
	0xbd, 0xb2, 0x66, 0x4c, 0x0b, 0x36, 0x76, 0xf2, 0x18, 0xba, 0xa6, 0x64, 0xde, 0x29, 0xdf, 0x84,
	0x6e, 0x29, 0x8f, 0xcd, 0xdc, 0xe3, 0x24, 0x9a, 0xb3, 0x20, 0x7c, 0x22, 0xad, 0x7e, 0xc7, 0x80,
	0x95, 0x94, 0x90, 0xef, 0xa0, 0x6d, 0x14, 0xf2, 0x25, 0x4c, 0xe8, 0x1d, 0xe5, 0xfb, 0xbf, 0xdc,
	0x77, 0xef, 0xc4, 0x31, 0xeb, 0xa5, 0x0b, 0x1e, 0x72, 0x03, 0xb1, 0x72, 0xa5, 0x7a, 0xa8, 0x51,
	0x82, 0x1d, 0xa4, 0xee, 0xea, 0x26, 0x9b, 0xf2, 0x59, 0xef, 0x25, 0xac, 0x5d, 0x0b, 0xe5, 0xf6,
	0xe2, 0x8e, 0xee, 0xc5, 0x3b, 0xc5, 0xf7, 0xc2, 0x5c, 0x3b, 0xe9, 0xf2, 0x2c, 0x1c, 0x47, 0x4e,
	0x6f, 0x3e, 0x6e, 0x83, 0x9a, 0x1e, 0x83, 0x41, 0x2a, 0x30, 0xf1, 0xb6, 0xa1, 0x61, 0x41, 0x39,
	0xa5, 0x92, 0x43, 0xc9, 0x3b, 0x85, 0x66, 0x76, 0x7c, 0x1f, 0xe9, 0x3b, 0xc5, 0xf6, 0xb2, 0xb2,
	0xdc, 0x5e, 0xbc, 0x23, 0x58, 0x5d, 0x3a, 0xd3, 0x8f, 0x04, 0xcb, 0xb2, 0xbb, 0xe2, 0x64, 0xd7,
	0xbb, 0x0f, 0xd5, 0xa3, 0x59, 0xc0, 0x12, 0xb2, 0x0d, 0xad, 0x3c, 0xb2, 0xa5, 0xeb, 0xaa, 0xf6,
	0x7f, 0x2d, 0xc3, 0xea, 0x71, 0x10, 0x0d, 0x04, 0x47, 0x7c, 0x8d, 0xfc, 0x7d, 0x30, 0x44, 0x72,
	0x00, 0x35, 0x3d, 0x92, 0x92, 0x75, 0x7d, 0x3a, 0x85, 0xa9, 0xb9, 0xb7, 0x51, 0x54, 0x9a, 0x87,
	0xe8, 0x10, 0xea, 0x66, 0x42, 0x24, 0x1b, 0xd9, 0x4b, 0xe0, 0x0c, 0xa7, 0xbd, 0xcd, 0x25, 0xad,
	0xf1, 0x7b, 0x08, 0x55, 0x7d, 0x62, 0xc4, 0xd6, 0x76, 0x3e, 0x22, 0xf6, 0xd6, 0x0b, 0x3a, 0xe3,
	0xb1, 0x0b, 0x15, 0x99, 0x09, 0xb2, 0x96, 0xa7, 0xce, 0xe2, 0x89, 0xab, 0x32, 0xf0, 0x03, 0xa8,
	0x99, 0xe7, 0xc5, 0x44, 0x2b, 0x0c, 0x57, 0x76, 0x37, 0x4b, 0x83, 0xcf, 0x2e, 0x54, 0xe4, 0xfb,
	0x6f, 0xd7, 0x70, 0xc6, 0x9b, 0x1e, 0xb9, 0x3e, 0xbc, 0x90, 0x63, 0x68, 0x39, 0x8f, 0x33, 0x31,
	0x95, 0x79, 0xfd, 0x65, 0xef, 0xdd, 0xbd, 0xc1, 0xa2, 0x63, 0x0c, 0x6a, 0xea, 0x2f, 0xe5, 0xe0,
	0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xda, 0x67, 0x24, 0xc2, 0xc4, 0x0c, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BiobtreeServiceClient is the client API for BiobtreeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BiobtreeServiceClient interface {
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	Mapping(ctx context.Context, in *MappingRequest, opts ...grpc.CallOption) (*MappingResponse, error)
	Entry(ctx context.Context, in *EntryRequest, opts ...grpc.CallOption) (*EntryResponse, error)
	Page(ctx context.Context, in *PageRequest, opts ...grpc.CallOption) (*PageResponse, error)
	Filter(ctx context.Context, in *FilterRequest, opts ...grpc.CallOption) (*FilterResponse, error)
	Meta(ctx context.Context, in *MetaRequest, opts ...grpc.CallOption) (*MetaResponse, error)
	ListGenomes(ctx context.Context, in *ListGenomesRequest, opts ...grpc.CallOption) (*ListGenomesResponse, error)
}

type biobtreeServiceClient struct {
	cc *grpc.ClientConn
}

func NewBiobtreeServiceClient(cc *grpc.ClientConn) BiobtreeServiceClient {
	return &biobtreeServiceClient{cc}
}

func (c *biobtreeServiceClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, "/pbuf.BiobtreeService/Search", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *biobtreeServiceClient) Mapping(ctx context.Context, in *MappingRequest, opts ...grpc.CallOption) (*MappingResponse, error) {
	out := new(MappingResponse)
	err := c.cc.Invoke(ctx, "/pbuf.BiobtreeService/Mapping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *biobtreeServiceClient) Entry(ctx context.Context, in *EntryRequest, opts ...grpc.CallOption) (*EntryResponse, error) {
	out := new(EntryResponse)
	err := c.cc.Invoke(ctx, "/pbuf.BiobtreeService/Entry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *biobtreeServiceClient) Page(ctx context.Context, in *PageRequest, opts ...grpc.CallOption) (*PageResponse, error) {
	out := new(PageResponse)
	err := c.cc.Invoke(ctx, "/pbuf.BiobtreeService/Page", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *biobtreeServiceClient) Filter(ctx context.Context, in *FilterRequest, opts ...grpc.CallOption) (*FilterResponse, error) {
	out := new(FilterResponse)
	err := c.cc.Invoke(ctx, "/pbuf.BiobtreeService/Filter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *biobtreeServiceClient) Meta(ctx context.Context, in *MetaRequest, opts ...grpc.CallOption) (*MetaResponse, error) {
	out := new(MetaResponse)
	err := c.cc.Invoke(ctx, "/pbuf.BiobtreeService/Meta", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *biobtreeServiceClient) ListGenomes(ctx context.Context, in *ListGenomesRequest, opts ...grpc.CallOption) (*ListGenomesResponse, error) {
	out := new(ListGenomesResponse)
	err := c.cc.Invoke(ctx, "/pbuf.BiobtreeService/ListGenomes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BiobtreeServiceServer is the server API for BiobtreeService service.
type BiobtreeServiceServer interface {
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	Mapping(context.Context, *MappingRequest) (*MappingResponse, error)
	Entry(context.Context, *EntryRequest) (*EntryResponse, error)
	Page(context.Context, *PageRequest) (*PageResponse, error)
	Filter(context.Context, *FilterRequest) (*FilterResponse, error)
	Meta(context.Context, *MetaRequest) (*MetaResponse, error)
	ListGenomes(context.Context, *ListGenomesRequest) (*ListGenomesResponse, error)
}

func RegisterBiobtreeServiceServer(s *grpc.Server, srv BiobtreeServiceServer) {
	s.RegisterService(&_BiobtreeService_serviceDesc, srv)
}

func _BiobtreeService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BiobtreeServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbuf.BiobtreeService/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BiobtreeServiceServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BiobtreeService_Mapping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MappingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BiobtreeServiceServer).Mapping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbuf.BiobtreeService/Mapping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BiobtreeServiceServer).Mapping(ctx, req.(*MappingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BiobtreeService_Entry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BiobtreeServiceServer).Entry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbuf.BiobtreeService/Entry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BiobtreeServiceServer).Entry(ctx, req.(*EntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BiobtreeService_Page_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BiobtreeServiceServer).Page(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbuf.BiobtreeService/Page",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BiobtreeServiceServer).Page(ctx, req.(*PageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BiobtreeService_Filter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FilterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BiobtreeServiceServer).Filter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbuf.BiobtreeService/Filter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BiobtreeServiceServer).Filter(ctx, req.(*FilterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BiobtreeService_Meta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BiobtreeServiceServer).Meta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbuf.BiobtreeService/Meta",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BiobtreeServiceServer).Meta(ctx, req.(*MetaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BiobtreeService_ListGenomes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGenomesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BiobtreeServiceServer).ListGenomes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbuf.BiobtreeService/ListGenomes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BiobtreeServiceServer).ListGenomes(ctx, req.(*ListGenomesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BiobtreeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pbuf.BiobtreeService",
	HandlerType: (*BiobtreeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _BiobtreeService_Search_Handler,
		},
		{
			MethodName: "Mapping",
			Handler:    _BiobtreeService_Mapping_Handler,
		},
		{
			MethodName: "Entry",
			Handler:    _BiobtreeService_Entry_Handler,
		},
		{
			MethodName: "Page",
			Handler:    _BiobtreeService_Page_Handler,
		},
		{
			MethodName: "Filter",
			Handler:    _BiobtreeService_Filter_Handler,
		},
		{
			MethodName: "Meta",
			Handler:    _BiobtreeService_Meta_Handler,
		},
		{
			MethodName: "ListGenomes",
			Handler:    _BiobtreeService_ListGenomes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app.proto",
}
