strategy:
  matrix:
    linux:
      imageName: "ubuntu-16.04"
    mac:
      imageName: "macOS-latest"
    windows:
      imageName: "windows-2019"
pool:
  vmImage: $(imageName)

variables:
  biobtree_latest_version: "v1.2.0"
  biobtree_latest_linux: "https://github.com/tamerh/biobtree/releases/download/$(biobtree_latest_version)/biobtree_Linux_64bit.tar.gz"
  biobtree_latest_mac: "https://github.com/tamerh/biobtree/releases/download/$(biobtree_latest_version)/biobtree_MacOS_64bit.tar.gz"
  biobtree_latest_windows: "https://github.com/tamerh/biobtree/releases/download/$(biobtree_latest_version)/biobtree_Windows_64bit.zip"

steps:
  - task: Bash@3
    inputs:
      targetType: "inline"
      script: curl -O -J -L $(biobtree_latest_linux) && tar -xzvf biobtree_Linux_64bit.tar.gz && chmod 777 biobtree && ./biobtree -d hgnc update && ./biobtree -d hgnc generate
    condition: eq(variables['imageName'],'ubuntu-16.04')
    displayName: Linux test default datasets

  - task: Bash@3
    inputs:
      targetType: "inline"
      script: curl -O -J -L $(biobtree_latest_mac) && tar -xzvf biobtree_MacOS_64bit.tar.gz && ./biobtree -d hgnc update && ./biobtree -d hgnc generate
    condition: eq(variables['imageName'],'macos-10.13')
    displayName: MacOS test default datasets

  - task: Bash@3
    inputs:
      targetType: "inline"
      script: curl -O -J -L $(biobtree_latest_windows) && unzip biobtree_Windows_64bit.zip
    condition: eq(variables['imageName'],'windows-2019')
    displayName: Windows download file

  - script: biobtree.exe -d hgnc update
    condition: eq(variables['imageName'],'windows-2019')
    displayName: Windows test uniprot_reviewed dataset update
    
  - script: biobtree.exe generate
    condition: eq(variables['imageName'],'windows-2019')
    displayName: Windows test default dataset generate
