// Code generated by protoc-gen-go. DO NOT EDIT.
// source: app.proto

package pbuf

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BiobtreeGetRequest struct {
	Keywords             []string `protobuf:"bytes,1,rep,name=keywords,proto3" json:"keywords,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BiobtreeGetRequest) Reset()         { *m = BiobtreeGetRequest{} }
func (m *BiobtreeGetRequest) String() string { return proto.CompactTextString(m) }
func (*BiobtreeGetRequest) ProtoMessage()    {}
func (*BiobtreeGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{0}
}

func (m *BiobtreeGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BiobtreeGetRequest.Unmarshal(m, b)
}
func (m *BiobtreeGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BiobtreeGetRequest.Marshal(b, m, deterministic)
}
func (m *BiobtreeGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BiobtreeGetRequest.Merge(m, src)
}
func (m *BiobtreeGetRequest) XXX_Size() int {
	return xxx_messageInfo_BiobtreeGetRequest.Size(m)
}
func (m *BiobtreeGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BiobtreeGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BiobtreeGetRequest proto.InternalMessageInfo

func (m *BiobtreeGetRequest) GetKeywords() []string {
	if m != nil {
		return m.Keywords
	}
	return nil
}

type BiobtreeGetPageRequest struct {
	Keyword              string   `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Dataset              int32    `protobuf:"varint,2,opt,name=dataset,proto3" json:"dataset,omitempty"`
	Page                 int32    `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Total                int32    `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BiobtreeGetPageRequest) Reset()         { *m = BiobtreeGetPageRequest{} }
func (m *BiobtreeGetPageRequest) String() string { return proto.CompactTextString(m) }
func (*BiobtreeGetPageRequest) ProtoMessage()    {}
func (*BiobtreeGetPageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{1}
}

func (m *BiobtreeGetPageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BiobtreeGetPageRequest.Unmarshal(m, b)
}
func (m *BiobtreeGetPageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BiobtreeGetPageRequest.Marshal(b, m, deterministic)
}
func (m *BiobtreeGetPageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BiobtreeGetPageRequest.Merge(m, src)
}
func (m *BiobtreeGetPageRequest) XXX_Size() int {
	return xxx_messageInfo_BiobtreeGetPageRequest.Size(m)
}
func (m *BiobtreeGetPageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BiobtreeGetPageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BiobtreeGetPageRequest proto.InternalMessageInfo

func (m *BiobtreeGetPageRequest) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

func (m *BiobtreeGetPageRequest) GetDataset() int32 {
	if m != nil {
		return m.Dataset
	}
	return 0
}

func (m *BiobtreeGetPageRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *BiobtreeGetPageRequest) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type BiobtreeFilterRequest struct {
	Keyword              string   `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Dataset              int32    `protobuf:"varint,2,opt,name=dataset,proto3" json:"dataset,omitempty"`
	Filters              []uint32 `protobuf:"varint,3,rep,packed,name=filters,proto3" json:"filters,omitempty"`
	Page                 int32    `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BiobtreeFilterRequest) Reset()         { *m = BiobtreeFilterRequest{} }
func (m *BiobtreeFilterRequest) String() string { return proto.CompactTextString(m) }
func (*BiobtreeFilterRequest) ProtoMessage()    {}
func (*BiobtreeFilterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{2}
}

func (m *BiobtreeFilterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BiobtreeFilterRequest.Unmarshal(m, b)
}
func (m *BiobtreeFilterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BiobtreeFilterRequest.Marshal(b, m, deterministic)
}
func (m *BiobtreeFilterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BiobtreeFilterRequest.Merge(m, src)
}
func (m *BiobtreeFilterRequest) XXX_Size() int {
	return xxx_messageInfo_BiobtreeFilterRequest.Size(m)
}
func (m *BiobtreeFilterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BiobtreeFilterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BiobtreeFilterRequest proto.InternalMessageInfo

func (m *BiobtreeFilterRequest) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

func (m *BiobtreeFilterRequest) GetDataset() int32 {
	if m != nil {
		return m.Dataset
	}
	return 0
}

func (m *BiobtreeFilterRequest) GetFilters() []uint32 {
	if m != nil {
		return m.Filters
	}
	return nil
}

func (m *BiobtreeFilterRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

type BiobtreeMetaRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BiobtreeMetaRequest) Reset()         { *m = BiobtreeMetaRequest{} }
func (m *BiobtreeMetaRequest) String() string { return proto.CompactTextString(m) }
func (*BiobtreeMetaRequest) ProtoMessage()    {}
func (*BiobtreeMetaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{3}
}

func (m *BiobtreeMetaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BiobtreeMetaRequest.Unmarshal(m, b)
}
func (m *BiobtreeMetaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BiobtreeMetaRequest.Marshal(b, m, deterministic)
}
func (m *BiobtreeMetaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BiobtreeMetaRequest.Merge(m, src)
}
func (m *BiobtreeMetaRequest) XXX_Size() int {
	return xxx_messageInfo_BiobtreeMetaRequest.Size(m)
}
func (m *BiobtreeMetaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BiobtreeMetaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BiobtreeMetaRequest proto.InternalMessageInfo

type BiobtreeGetResponse struct {
	Results              []*Result `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *BiobtreeGetResponse) Reset()         { *m = BiobtreeGetResponse{} }
func (m *BiobtreeGetResponse) String() string { return proto.CompactTextString(m) }
func (*BiobtreeGetResponse) ProtoMessage()    {}
func (*BiobtreeGetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{4}
}

func (m *BiobtreeGetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BiobtreeGetResponse.Unmarshal(m, b)
}
func (m *BiobtreeGetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BiobtreeGetResponse.Marshal(b, m, deterministic)
}
func (m *BiobtreeGetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BiobtreeGetResponse.Merge(m, src)
}
func (m *BiobtreeGetResponse) XXX_Size() int {
	return xxx_messageInfo_BiobtreeGetResponse.Size(m)
}
func (m *BiobtreeGetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BiobtreeGetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BiobtreeGetResponse proto.InternalMessageInfo

func (m *BiobtreeGetResponse) GetResults() []*Result {
	if m != nil {
		return m.Results
	}
	return nil
}

type BiobtreeGetPageResponse struct {
	Result               *Result  `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BiobtreeGetPageResponse) Reset()         { *m = BiobtreeGetPageResponse{} }
func (m *BiobtreeGetPageResponse) String() string { return proto.CompactTextString(m) }
func (*BiobtreeGetPageResponse) ProtoMessage()    {}
func (*BiobtreeGetPageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{5}
}

func (m *BiobtreeGetPageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BiobtreeGetPageResponse.Unmarshal(m, b)
}
func (m *BiobtreeGetPageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BiobtreeGetPageResponse.Marshal(b, m, deterministic)
}
func (m *BiobtreeGetPageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BiobtreeGetPageResponse.Merge(m, src)
}
func (m *BiobtreeGetPageResponse) XXX_Size() int {
	return xxx_messageInfo_BiobtreeGetPageResponse.Size(m)
}
func (m *BiobtreeGetPageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BiobtreeGetPageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BiobtreeGetPageResponse proto.InternalMessageInfo

func (m *BiobtreeGetPageResponse) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

type BiobtreeFilterResponse struct {
	Result               *Result  `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BiobtreeFilterResponse) Reset()         { *m = BiobtreeFilterResponse{} }
func (m *BiobtreeFilterResponse) String() string { return proto.CompactTextString(m) }
func (*BiobtreeFilterResponse) ProtoMessage()    {}
func (*BiobtreeFilterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{6}
}

func (m *BiobtreeFilterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BiobtreeFilterResponse.Unmarshal(m, b)
}
func (m *BiobtreeFilterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BiobtreeFilterResponse.Marshal(b, m, deterministic)
}
func (m *BiobtreeFilterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BiobtreeFilterResponse.Merge(m, src)
}
func (m *BiobtreeFilterResponse) XXX_Size() int {
	return xxx_messageInfo_BiobtreeFilterResponse.Size(m)
}
func (m *BiobtreeFilterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BiobtreeFilterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BiobtreeFilterResponse proto.InternalMessageInfo

func (m *BiobtreeFilterResponse) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

type BiobtreeMetaResponse struct {
	Results              map[string]*BiobtreeMetaKeyValue `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *BiobtreeMetaResponse) Reset()         { *m = BiobtreeMetaResponse{} }
func (m *BiobtreeMetaResponse) String() string { return proto.CompactTextString(m) }
func (*BiobtreeMetaResponse) ProtoMessage()    {}
func (*BiobtreeMetaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{7}
}

func (m *BiobtreeMetaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BiobtreeMetaResponse.Unmarshal(m, b)
}
func (m *BiobtreeMetaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BiobtreeMetaResponse.Marshal(b, m, deterministic)
}
func (m *BiobtreeMetaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BiobtreeMetaResponse.Merge(m, src)
}
func (m *BiobtreeMetaResponse) XXX_Size() int {
	return xxx_messageInfo_BiobtreeMetaResponse.Size(m)
}
func (m *BiobtreeMetaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BiobtreeMetaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BiobtreeMetaResponse proto.InternalMessageInfo

func (m *BiobtreeMetaResponse) GetResults() map[string]*BiobtreeMetaKeyValue {
	if m != nil {
		return m.Results
	}
	return nil
}

type BiobtreeMetaKeyValue struct {
	Keyvalues            map[string]string `protobuf:"bytes,1,rep,name=keyvalues,proto3" json:"keyvalues,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *BiobtreeMetaKeyValue) Reset()         { *m = BiobtreeMetaKeyValue{} }
func (m *BiobtreeMetaKeyValue) String() string { return proto.CompactTextString(m) }
func (*BiobtreeMetaKeyValue) ProtoMessage()    {}
func (*BiobtreeMetaKeyValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{8}
}

func (m *BiobtreeMetaKeyValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BiobtreeMetaKeyValue.Unmarshal(m, b)
}
func (m *BiobtreeMetaKeyValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BiobtreeMetaKeyValue.Marshal(b, m, deterministic)
}
func (m *BiobtreeMetaKeyValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BiobtreeMetaKeyValue.Merge(m, src)
}
func (m *BiobtreeMetaKeyValue) XXX_Size() int {
	return xxx_messageInfo_BiobtreeMetaKeyValue.Size(m)
}
func (m *BiobtreeMetaKeyValue) XXX_DiscardUnknown() {
	xxx_messageInfo_BiobtreeMetaKeyValue.DiscardUnknown(m)
}

var xxx_messageInfo_BiobtreeMetaKeyValue proto.InternalMessageInfo

func (m *BiobtreeMetaKeyValue) GetKeyvalues() map[string]string {
	if m != nil {
		return m.Keyvalues
	}
	return nil
}

type Result struct {
	//string identifier = 1;
	Results              []*Xref  `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{9}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetResults() []*Xref {
	if m != nil {
		return m.Results
	}
	return nil
}

type Xref struct {
	DomainId uint32 `protobuf:"varint,1,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	//uint64 uid=2;
	Count        uint32             `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	IsLink       bool               `protobuf:"varint,3,opt,name=is_link,json=isLink,proto3" json:"is_link,omitempty"`
	Entries      []*XrefEntry       `protobuf:"bytes,4,rep,name=entries,proto3" json:"entries,omitempty"`
	DomainCounts []*XrefDomainCount `protobuf:"bytes,5,rep,name=domain_counts,json=domainCounts,proto3" json:"domain_counts,omitempty"`
	Attributes   []*XrefProp        `protobuf:"bytes,6,rep,name=attributes,proto3" json:"attributes,omitempty"`
	// these 2 fields are transient fields not saved to database
	Identifier           string   `protobuf:"bytes,7,opt,name=identifier,proto3" json:"identifier,omitempty"`
	SpecialKeyword       string   `protobuf:"bytes,8,opt,name=specialKeyword,proto3" json:"specialKeyword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Xref) Reset()         { *m = Xref{} }
func (m *Xref) String() string { return proto.CompactTextString(m) }
func (*Xref) ProtoMessage()    {}
func (*Xref) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{10}
}

func (m *Xref) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Xref.Unmarshal(m, b)
}
func (m *Xref) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Xref.Marshal(b, m, deterministic)
}
func (m *Xref) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Xref.Merge(m, src)
}
func (m *Xref) XXX_Size() int {
	return xxx_messageInfo_Xref.Size(m)
}
func (m *Xref) XXX_DiscardUnknown() {
	xxx_messageInfo_Xref.DiscardUnknown(m)
}

var xxx_messageInfo_Xref proto.InternalMessageInfo

func (m *Xref) GetDomainId() uint32 {
	if m != nil {
		return m.DomainId
	}
	return 0
}

func (m *Xref) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *Xref) GetIsLink() bool {
	if m != nil {
		return m.IsLink
	}
	return false
}

func (m *Xref) GetEntries() []*XrefEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

func (m *Xref) GetDomainCounts() []*XrefDomainCount {
	if m != nil {
		return m.DomainCounts
	}
	return nil
}

func (m *Xref) GetAttributes() []*XrefProp {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *Xref) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *Xref) GetSpecialKeyword() string {
	if m != nil {
		return m.SpecialKeyword
	}
	return ""
}

type XrefProp struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Values               []string `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *XrefProp) Reset()         { *m = XrefProp{} }
func (m *XrefProp) String() string { return proto.CompactTextString(m) }
func (*XrefProp) ProtoMessage()    {}
func (*XrefProp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{11}
}

func (m *XrefProp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XrefProp.Unmarshal(m, b)
}
func (m *XrefProp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XrefProp.Marshal(b, m, deterministic)
}
func (m *XrefProp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XrefProp.Merge(m, src)
}
func (m *XrefProp) XXX_Size() int {
	return xxx_messageInfo_XrefProp.Size(m)
}
func (m *XrefProp) XXX_DiscardUnknown() {
	xxx_messageInfo_XrefProp.DiscardUnknown(m)
}

var xxx_messageInfo_XrefProp proto.InternalMessageInfo

func (m *XrefProp) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *XrefProp) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

type XrefEntry struct {
	DomainId             uint32   `protobuf:"varint,1,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	XrefId               string   `protobuf:"bytes,2,opt,name=xref_id,json=xrefId,proto3" json:"xref_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *XrefEntry) Reset()         { *m = XrefEntry{} }
func (m *XrefEntry) String() string { return proto.CompactTextString(m) }
func (*XrefEntry) ProtoMessage()    {}
func (*XrefEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{12}
}

func (m *XrefEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XrefEntry.Unmarshal(m, b)
}
func (m *XrefEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XrefEntry.Marshal(b, m, deterministic)
}
func (m *XrefEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XrefEntry.Merge(m, src)
}
func (m *XrefEntry) XXX_Size() int {
	return xxx_messageInfo_XrefEntry.Size(m)
}
func (m *XrefEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_XrefEntry.DiscardUnknown(m)
}

var xxx_messageInfo_XrefEntry proto.InternalMessageInfo

func (m *XrefEntry) GetDomainId() uint32 {
	if m != nil {
		return m.DomainId
	}
	return 0
}

func (m *XrefEntry) GetXrefId() string {
	if m != nil {
		return m.XrefId
	}
	return ""
}

type XrefDomainCount struct {
	DomainId             uint32   `protobuf:"varint,1,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	Count                uint32   `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *XrefDomainCount) Reset()         { *m = XrefDomainCount{} }
func (m *XrefDomainCount) String() string { return proto.CompactTextString(m) }
func (*XrefDomainCount) ProtoMessage()    {}
func (*XrefDomainCount) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{13}
}

func (m *XrefDomainCount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XrefDomainCount.Unmarshal(m, b)
}
func (m *XrefDomainCount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XrefDomainCount.Marshal(b, m, deterministic)
}
func (m *XrefDomainCount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XrefDomainCount.Merge(m, src)
}
func (m *XrefDomainCount) XXX_Size() int {
	return xxx_messageInfo_XrefDomainCount.Size(m)
}
func (m *XrefDomainCount) XXX_DiscardUnknown() {
	xxx_messageInfo_XrefDomainCount.DiscardUnknown(m)
}

var xxx_messageInfo_XrefDomainCount proto.InternalMessageInfo

func (m *XrefDomainCount) GetDomainId() uint32 {
	if m != nil {
		return m.DomainId
	}
	return 0
}

func (m *XrefDomainCount) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func init() {
	proto.RegisterType((*BiobtreeGetRequest)(nil), "pbuf.BiobtreeGetRequest")
	proto.RegisterType((*BiobtreeGetPageRequest)(nil), "pbuf.BiobtreeGetPageRequest")
	proto.RegisterType((*BiobtreeFilterRequest)(nil), "pbuf.BiobtreeFilterRequest")
	proto.RegisterType((*BiobtreeMetaRequest)(nil), "pbuf.BiobtreeMetaRequest")
	proto.RegisterType((*BiobtreeGetResponse)(nil), "pbuf.BiobtreeGetResponse")
	proto.RegisterType((*BiobtreeGetPageResponse)(nil), "pbuf.BiobtreeGetPageResponse")
	proto.RegisterType((*BiobtreeFilterResponse)(nil), "pbuf.BiobtreeFilterResponse")
	proto.RegisterType((*BiobtreeMetaResponse)(nil), "pbuf.BiobtreeMetaResponse")
	proto.RegisterMapType((map[string]*BiobtreeMetaKeyValue)(nil), "pbuf.BiobtreeMetaResponse.ResultsEntry")
	proto.RegisterType((*BiobtreeMetaKeyValue)(nil), "pbuf.BiobtreeMetaKeyValue")
	proto.RegisterMapType((map[string]string)(nil), "pbuf.BiobtreeMetaKeyValue.KeyvaluesEntry")
	proto.RegisterType((*Result)(nil), "pbuf.Result")
	proto.RegisterType((*Xref)(nil), "pbuf.Xref")
	proto.RegisterType((*XrefProp)(nil), "pbuf.XrefProp")
	proto.RegisterType((*XrefEntry)(nil), "pbuf.XrefEntry")
	proto.RegisterType((*XrefDomainCount)(nil), "pbuf.XrefDomainCount")
}

func init() { proto.RegisterFile("app.proto", fileDescriptor_e0f9056a14b86d47) }

var fileDescriptor_e0f9056a14b86d47 = []byte{
	// 669 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0x5b, 0x4f, 0x13, 0x41,
	0x14, 0x4e, 0x6f, 0xbb, 0xdd, 0x03, 0x05, 0x33, 0x72, 0x59, 0x16, 0x34, 0xcd, 0x86, 0x60, 0x79,
	0x69, 0x08, 0xfa, 0x60, 0x88, 0x68, 0x10, 0x84, 0x10, 0x34, 0x21, 0x63, 0x42, 0x7c, 0x23, 0x5b,
	0xf6, 0x94, 0x4c, 0x5a, 0x77, 0xd7, 0x99, 0x29, 0xda, 0x9f, 0xe2, 0x83, 0x3f, 0x82, 0x7f, 0x68,
	0x76, 0x2e, 0xdd, 0x6d, 0x29, 0x26, 0xea, 0xdb, 0x9e, 0xf3, 0x7d, 0xe7, 0x7e, 0xe6, 0x2c, 0x78,
	0x51, 0x96, 0x75, 0x33, 0x9e, 0xca, 0x94, 0xd4, 0xb3, 0xde, 0xa8, 0x1f, 0xee, 0x01, 0x79, 0xcf,
	0xd2, 0x9e, 0xe4, 0x88, 0x67, 0x28, 0x29, 0x7e, 0x1b, 0xa1, 0x90, 0x24, 0x80, 0xe6, 0x00, 0xc7,
	0xdf, 0x53, 0x1e, 0x0b, 0xbf, 0xd2, 0xae, 0x75, 0x3c, 0x3a, 0x91, 0xc3, 0x3b, 0x58, 0x2b, 0x59,
	0x5c, 0x46, 0xb7, 0x68, 0xad, 0x7c, 0x70, 0x0d, 0xcb, 0xaf, 0xb4, 0x2b, 0x1d, 0x8f, 0x5a, 0x31,
	0x47, 0xe2, 0x48, 0x46, 0x02, 0xa5, 0x5f, 0x6d, 0x57, 0x3a, 0x0d, 0x6a, 0x45, 0x42, 0xa0, 0x9e,
	0x45, 0xb7, 0xe8, 0xd7, 0x94, 0x5a, 0x7d, 0x93, 0x15, 0x68, 0xc8, 0x54, 0x46, 0x43, 0xbf, 0xae,
	0x94, 0x5a, 0x08, 0xc7, 0xb0, 0x6a, 0xe3, 0x9e, 0xb2, 0xa1, 0x44, 0xfe, 0x3f, 0x61, 0x7d, 0x70,
	0xfb, 0xca, 0x89, 0xf0, 0x6b, 0xed, 0x5a, 0xa7, 0x45, 0xad, 0x38, 0x49, 0xa8, 0x5e, 0x24, 0x14,
	0xae, 0xc2, 0x53, 0x1b, 0xfa, 0x13, 0xca, 0xc8, 0x04, 0x0e, 0x0f, 0x0b, 0xb5, 0xea, 0x9d, 0xc8,
	0xd2, 0x44, 0x20, 0xd9, 0x01, 0x97, 0xa3, 0x18, 0x0d, 0xa5, 0xee, 0xdd, 0xc2, 0xfe, 0x62, 0x37,
	0x6f, 0x75, 0x97, 0x2a, 0x25, 0xb5, 0x60, 0xf8, 0x0e, 0xd6, 0x1f, 0x34, 0xd2, 0xb8, 0xd8, 0x06,
	0x47, 0xb3, 0x54, 0x45, 0xb3, 0x1e, 0x0c, 0x16, 0xbe, 0x2d, 0x26, 0x61, 0x3b, 0xf2, 0x57, 0xf6,
	0xf7, 0x15, 0x58, 0x99, 0xae, 0xcb, 0x98, 0x1f, 0xcd, 0x56, 0xf0, 0x42, 0xdb, 0xcf, 0x23, 0x1b,
	0xa7, 0xe2, 0x43, 0x22, 0xf9, 0x78, 0x52, 0x5c, 0x70, 0x05, 0x8b, 0x65, 0x80, 0x3c, 0x81, 0xda,
	0x00, 0xc7, 0x66, 0x40, 0xf9, 0x27, 0xd9, 0x83, 0xc6, 0x5d, 0x34, 0x1c, 0xa1, 0x1a, 0xcd, 0xc2,
	0x7e, 0xf0, 0x30, 0xc4, 0x05, 0x8e, 0xaf, 0x72, 0x06, 0xd5, 0xc4, 0x83, 0xea, 0xeb, 0x4a, 0xf8,
	0x6b, 0x26, 0x67, 0xcb, 0x21, 0x67, 0xe0, 0x0d, 0x70, 0xac, 0x88, 0x36, 0xeb, 0xdd, 0xc7, 0x5d,
	0x76, 0x2f, 0x2c, 0x57, 0xe7, 0x5d, 0xd8, 0x06, 0x6f, 0x60, 0x69, 0x1a, 0x9c, 0x93, 0xfb, 0x4a,
	0x39, 0x77, 0xaf, 0x9c, 0x5f, 0x17, 0x1c, 0x5d, 0x37, 0xd9, 0x9e, 0x6d, 0x22, 0xe8, 0x74, 0xbe,
	0x70, 0xec, 0x17, 0x4b, 0x70, 0x5f, 0x85, 0x7a, 0xae, 0x21, 0x9b, 0xe0, 0xc5, 0xe9, 0xd7, 0x88,
	0x25, 0xd7, 0x4c, 0xef, 0x71, 0x8b, 0x36, 0xb5, 0xe2, 0x3c, 0xce, 0xe3, 0xdd, 0xa4, 0xa3, 0x44,
	0xaf, 0x71, 0x8b, 0x6a, 0x81, 0xac, 0x83, 0xcb, 0xc4, 0xf5, 0x90, 0x25, 0x03, 0xf5, 0x7c, 0x9a,
	0xd4, 0x61, 0xe2, 0x23, 0x4b, 0x06, 0x64, 0x17, 0x5c, 0x4c, 0x24, 0x67, 0x28, 0xfc, 0xba, 0x0a,
	0xbd, 0x5c, 0x84, 0x36, 0x73, 0x32, 0x38, 0x39, 0x80, 0x96, 0x09, 0xab, 0x7c, 0x0a, 0xbf, 0xa1,
	0x0c, 0x56, 0x0b, 0x83, 0x13, 0x05, 0x1f, 0xe7, 0x28, 0x5d, 0x8c, 0x0b, 0x41, 0x90, 0x2e, 0x40,
	0x24, 0x25, 0x67, 0xbd, 0x91, 0x44, 0xe1, 0x3b, 0xca, 0x70, 0xa9, 0x30, 0xbc, 0xe4, 0x69, 0x46,
	0x4b, 0x0c, 0xf2, 0x1c, 0x80, 0xc5, 0x98, 0x48, 0xd6, 0x67, 0xc8, 0x7d, 0x57, 0xb5, 0xae, 0xa4,
	0x21, 0x3b, 0xb0, 0x24, 0x32, 0xbc, 0x61, 0xd1, 0xf0, 0xc2, 0xbc, 0xe7, 0xa6, 0xe2, 0xcc, 0x68,
	0xc3, 0x57, 0xd0, 0xb4, 0xfe, 0xe7, 0xcc, 0x66, 0x0d, 0x1c, 0xb3, 0x05, 0x55, 0x75, 0xb9, 0x8c,
	0x14, 0x1e, 0x81, 0x37, 0xa9, 0xff, 0xcf, 0xdd, 0x5e, 0x07, 0xf7, 0x07, 0xc7, 0x7e, 0x0e, 0xe9,
	0xf9, 0x3a, 0xb9, 0x78, 0x1e, 0x87, 0x27, 0xb0, 0x3c, 0xd3, 0x91, 0x7f, 0x18, 0xdb, 0xfe, 0xcf,
	0x2a, 0x2c, 0xdb, 0x9d, 0xfc, 0x8c, 0xfc, 0x8e, 0xdd, 0x20, 0x39, 0x80, 0xda, 0x59, 0x7e, 0x96,
	0xa6, 0x37, 0xb6, 0xb8, 0xc8, 0xc1, 0xc6, 0x1c, 0xc4, 0xbc, 0xd6, 0x53, 0x70, 0xcd, 0xfd, 0x20,
	0x5b, 0x0f, 0x58, 0xa5, 0xfb, 0x1c, 0x3c, 0x7b, 0x04, 0x35, 0x7e, 0x8e, 0xc1, 0xd1, 0x67, 0x84,
	0x6c, 0x4e, 0x13, 0xa7, 0xce, 0x6d, 0xb0, 0x35, 0x1f, 0x34, 0x4e, 0x0e, 0xa1, 0x9e, 0xbf, 0x33,
	0xb2, 0x31, 0xef, 0x62, 0x68, 0x07, 0xc1, 0xe3, 0xc7, 0xa4, 0xe7, 0xa8, 0x7f, 0xd3, 0xcb, 0xdf,
	0x01, 0x00, 0x00, 0xff, 0xff, 0xc7, 0xee, 0x94, 0x84, 0xa8, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BiobtreeServiceClient is the client API for BiobtreeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BiobtreeServiceClient interface {
	Get(ctx context.Context, in *BiobtreeGetRequest, opts ...grpc.CallOption) (*BiobtreeGetResponse, error)
	GetPage(ctx context.Context, in *BiobtreeGetPageRequest, opts ...grpc.CallOption) (*BiobtreeGetPageResponse, error)
	Filter(ctx context.Context, in *BiobtreeFilterRequest, opts ...grpc.CallOption) (*BiobtreeFilterResponse, error)
	Meta(ctx context.Context, in *BiobtreeMetaRequest, opts ...grpc.CallOption) (*BiobtreeMetaResponse, error)
}

type biobtreeServiceClient struct {
	cc *grpc.ClientConn
}

func NewBiobtreeServiceClient(cc *grpc.ClientConn) BiobtreeServiceClient {
	return &biobtreeServiceClient{cc}
}

func (c *biobtreeServiceClient) Get(ctx context.Context, in *BiobtreeGetRequest, opts ...grpc.CallOption) (*BiobtreeGetResponse, error) {
	out := new(BiobtreeGetResponse)
	err := c.cc.Invoke(ctx, "/pbuf.BiobtreeService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *biobtreeServiceClient) GetPage(ctx context.Context, in *BiobtreeGetPageRequest, opts ...grpc.CallOption) (*BiobtreeGetPageResponse, error) {
	out := new(BiobtreeGetPageResponse)
	err := c.cc.Invoke(ctx, "/pbuf.BiobtreeService/GetPage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *biobtreeServiceClient) Filter(ctx context.Context, in *BiobtreeFilterRequest, opts ...grpc.CallOption) (*BiobtreeFilterResponse, error) {
	out := new(BiobtreeFilterResponse)
	err := c.cc.Invoke(ctx, "/pbuf.BiobtreeService/Filter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *biobtreeServiceClient) Meta(ctx context.Context, in *BiobtreeMetaRequest, opts ...grpc.CallOption) (*BiobtreeMetaResponse, error) {
	out := new(BiobtreeMetaResponse)
	err := c.cc.Invoke(ctx, "/pbuf.BiobtreeService/Meta", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BiobtreeServiceServer is the server API for BiobtreeService service.
type BiobtreeServiceServer interface {
	Get(context.Context, *BiobtreeGetRequest) (*BiobtreeGetResponse, error)
	GetPage(context.Context, *BiobtreeGetPageRequest) (*BiobtreeGetPageResponse, error)
	Filter(context.Context, *BiobtreeFilterRequest) (*BiobtreeFilterResponse, error)
	Meta(context.Context, *BiobtreeMetaRequest) (*BiobtreeMetaResponse, error)
}

func RegisterBiobtreeServiceServer(s *grpc.Server, srv BiobtreeServiceServer) {
	s.RegisterService(&_BiobtreeService_serviceDesc, srv)
}

func _BiobtreeService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BiobtreeGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BiobtreeServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbuf.BiobtreeService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BiobtreeServiceServer).Get(ctx, req.(*BiobtreeGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BiobtreeService_GetPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BiobtreeGetPageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BiobtreeServiceServer).GetPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbuf.BiobtreeService/GetPage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BiobtreeServiceServer).GetPage(ctx, req.(*BiobtreeGetPageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BiobtreeService_Filter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BiobtreeFilterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BiobtreeServiceServer).Filter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbuf.BiobtreeService/Filter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BiobtreeServiceServer).Filter(ctx, req.(*BiobtreeFilterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BiobtreeService_Meta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BiobtreeMetaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BiobtreeServiceServer).Meta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbuf.BiobtreeService/Meta",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BiobtreeServiceServer).Meta(ctx, req.(*BiobtreeMetaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BiobtreeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pbuf.BiobtreeService",
	HandlerType: (*BiobtreeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _BiobtreeService_Get_Handler,
		},
		{
			MethodName: "GetPage",
			Handler:    _BiobtreeService_GetPage_Handler,
		},
		{
			MethodName: "Filter",
			Handler:    _BiobtreeService_Filter_Handler,
		},
		{
			MethodName: "Meta",
			Handler:    _BiobtreeService_Meta_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app.proto",
}
