// Code generated by protoc-gen-go. DO NOT EDIT.
// source: app.proto

package pbuf

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SearchRequest struct {
	Terms                []string `protobuf:"bytes,1,rep,name=terms,proto3" json:"terms,omitempty"`
	Dataset              string   `protobuf:"bytes,2,opt,name=dataset,proto3" json:"dataset,omitempty"`
	Page                 string   `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	Query                string   `protobuf:"bytes,4,opt,name=query,proto3" json:"query,omitempty"`
	Detail               bool     `protobuf:"varint,5,opt,name=detail,proto3" json:"detail,omitempty"`
	Url                  bool     `protobuf:"varint,6,opt,name=url,proto3" json:"url,omitempty"`
	Mode                 string   `protobuf:"bytes,7,opt,name=mode,proto3" json:"mode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{0}
}

func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (m *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(m, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetTerms() []string {
	if m != nil {
		return m.Terms
	}
	return nil
}

func (m *SearchRequest) GetDataset() string {
	if m != nil {
		return m.Dataset
	}
	return ""
}

func (m *SearchRequest) GetPage() string {
	if m != nil {
		return m.Page
	}
	return ""
}

func (m *SearchRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *SearchRequest) GetDetail() bool {
	if m != nil {
		return m.Detail
	}
	return false
}

func (m *SearchRequest) GetUrl() bool {
	if m != nil {
		return m.Url
	}
	return false
}

func (m *SearchRequest) GetMode() string {
	if m != nil {
		return m.Mode
	}
	return ""
}

type SearchResponse struct {
	Results              *Result     `protobuf:"bytes,1,opt,name=results,proto3" json:"results,omitempty"`
	ResultsLite          *ResultLite `protobuf:"bytes,2,opt,name=results_lite,json=resultsLite,proto3" json:"results_lite,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SearchResponse) Reset()         { *m = SearchResponse{} }
func (m *SearchResponse) String() string { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()    {}
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{1}
}

func (m *SearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResponse.Unmarshal(m, b)
}
func (m *SearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResponse.Marshal(b, m, deterministic)
}
func (m *SearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResponse.Merge(m, src)
}
func (m *SearchResponse) XXX_Size() int {
	return xxx_messageInfo_SearchResponse.Size(m)
}
func (m *SearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResponse proto.InternalMessageInfo

func (m *SearchResponse) GetResults() *Result {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *SearchResponse) GetResultsLite() *ResultLite {
	if m != nil {
		return m.ResultsLite
	}
	return nil
}

type MappingRequest struct {
	Terms                []string `protobuf:"bytes,1,rep,name=terms,proto3" json:"terms,omitempty"`
	Dataset              string   `protobuf:"bytes,2,opt,name=dataset,proto3" json:"dataset,omitempty"`
	Query                string   `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	Page                 string   `protobuf:"bytes,4,opt,name=page,proto3" json:"page,omitempty"`
	Mode                 string   `protobuf:"bytes,5,opt,name=mode,proto3" json:"mode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MappingRequest) Reset()         { *m = MappingRequest{} }
func (m *MappingRequest) String() string { return proto.CompactTextString(m) }
func (*MappingRequest) ProtoMessage()    {}
func (*MappingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{2}
}

func (m *MappingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MappingRequest.Unmarshal(m, b)
}
func (m *MappingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MappingRequest.Marshal(b, m, deterministic)
}
func (m *MappingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MappingRequest.Merge(m, src)
}
func (m *MappingRequest) XXX_Size() int {
	return xxx_messageInfo_MappingRequest.Size(m)
}
func (m *MappingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MappingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MappingRequest proto.InternalMessageInfo

func (m *MappingRequest) GetTerms() []string {
	if m != nil {
		return m.Terms
	}
	return nil
}

func (m *MappingRequest) GetDataset() string {
	if m != nil {
		return m.Dataset
	}
	return ""
}

func (m *MappingRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *MappingRequest) GetPage() string {
	if m != nil {
		return m.Page
	}
	return ""
}

func (m *MappingRequest) GetMode() string {
	if m != nil {
		return m.Mode
	}
	return ""
}

type MappingResponse struct {
	Results              *MapFilterResult     `protobuf:"bytes,1,opt,name=results,proto3" json:"results,omitempty"`
	ResultsLite          *MapFilterResultLite `protobuf:"bytes,2,opt,name=results_lite,json=resultsLite,proto3" json:"results_lite,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *MappingResponse) Reset()         { *m = MappingResponse{} }
func (m *MappingResponse) String() string { return proto.CompactTextString(m) }
func (*MappingResponse) ProtoMessage()    {}
func (*MappingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{3}
}

func (m *MappingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MappingResponse.Unmarshal(m, b)
}
func (m *MappingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MappingResponse.Marshal(b, m, deterministic)
}
func (m *MappingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MappingResponse.Merge(m, src)
}
func (m *MappingResponse) XXX_Size() int {
	return xxx_messageInfo_MappingResponse.Size(m)
}
func (m *MappingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MappingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MappingResponse proto.InternalMessageInfo

func (m *MappingResponse) GetResults() *MapFilterResult {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *MappingResponse) GetResultsLite() *MapFilterResultLite {
	if m != nil {
		return m.ResultsLite
	}
	return nil
}

type EntryRequest struct {
	Identifier           string   `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Dataset              string   `protobuf:"bytes,2,opt,name=dataset,proto3" json:"dataset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EntryRequest) Reset()         { *m = EntryRequest{} }
func (m *EntryRequest) String() string { return proto.CompactTextString(m) }
func (*EntryRequest) ProtoMessage()    {}
func (*EntryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{4}
}

func (m *EntryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntryRequest.Unmarshal(m, b)
}
func (m *EntryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntryRequest.Marshal(b, m, deterministic)
}
func (m *EntryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntryRequest.Merge(m, src)
}
func (m *EntryRequest) XXX_Size() int {
	return xxx_messageInfo_EntryRequest.Size(m)
}
func (m *EntryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EntryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EntryRequest proto.InternalMessageInfo

func (m *EntryRequest) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *EntryRequest) GetDataset() string {
	if m != nil {
		return m.Dataset
	}
	return ""
}

type EntryResponse struct {
	Result               *Xref    `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EntryResponse) Reset()         { *m = EntryResponse{} }
func (m *EntryResponse) String() string { return proto.CompactTextString(m) }
func (*EntryResponse) ProtoMessage()    {}
func (*EntryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{5}
}

func (m *EntryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntryResponse.Unmarshal(m, b)
}
func (m *EntryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntryResponse.Marshal(b, m, deterministic)
}
func (m *EntryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntryResponse.Merge(m, src)
}
func (m *EntryResponse) XXX_Size() int {
	return xxx_messageInfo_EntryResponse.Size(m)
}
func (m *EntryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EntryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EntryResponse proto.InternalMessageInfo

func (m *EntryResponse) GetResult() *Xref {
	if m != nil {
		return m.Result
	}
	return nil
}

type PageRequest struct {
	Identifier           string   `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Dataset              string   `protobuf:"bytes,2,opt,name=dataset,proto3" json:"dataset,omitempty"`
	Page                 int32    `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Total                int32    `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PageRequest) Reset()         { *m = PageRequest{} }
func (m *PageRequest) String() string { return proto.CompactTextString(m) }
func (*PageRequest) ProtoMessage()    {}
func (*PageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{6}
}

func (m *PageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageRequest.Unmarshal(m, b)
}
func (m *PageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageRequest.Marshal(b, m, deterministic)
}
func (m *PageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageRequest.Merge(m, src)
}
func (m *PageRequest) XXX_Size() int {
	return xxx_messageInfo_PageRequest.Size(m)
}
func (m *PageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PageRequest proto.InternalMessageInfo

func (m *PageRequest) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *PageRequest) GetDataset() string {
	if m != nil {
		return m.Dataset
	}
	return ""
}

func (m *PageRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *PageRequest) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type PageResponse struct {
	Result               *Result  `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PageResponse) Reset()         { *m = PageResponse{} }
func (m *PageResponse) String() string { return proto.CompactTextString(m) }
func (*PageResponse) ProtoMessage()    {}
func (*PageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{7}
}

func (m *PageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageResponse.Unmarshal(m, b)
}
func (m *PageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageResponse.Marshal(b, m, deterministic)
}
func (m *PageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageResponse.Merge(m, src)
}
func (m *PageResponse) XXX_Size() int {
	return xxx_messageInfo_PageResponse.Size(m)
}
func (m *PageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PageResponse proto.InternalMessageInfo

func (m *PageResponse) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

type FilterRequest struct {
	Identifier           string   `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Dataset              string   `protobuf:"bytes,2,opt,name=dataset,proto3" json:"dataset,omitempty"`
	Filters              []string `protobuf:"bytes,3,rep,name=filters,proto3" json:"filters,omitempty"`
	Page                 int32    `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FilterRequest) Reset()         { *m = FilterRequest{} }
func (m *FilterRequest) String() string { return proto.CompactTextString(m) }
func (*FilterRequest) ProtoMessage()    {}
func (*FilterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{8}
}

func (m *FilterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilterRequest.Unmarshal(m, b)
}
func (m *FilterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilterRequest.Marshal(b, m, deterministic)
}
func (m *FilterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilterRequest.Merge(m, src)
}
func (m *FilterRequest) XXX_Size() int {
	return xxx_messageInfo_FilterRequest.Size(m)
}
func (m *FilterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FilterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FilterRequest proto.InternalMessageInfo

func (m *FilterRequest) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *FilterRequest) GetDataset() string {
	if m != nil {
		return m.Dataset
	}
	return ""
}

func (m *FilterRequest) GetFilters() []string {
	if m != nil {
		return m.Filters
	}
	return nil
}

func (m *FilterRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

type FilterResponse struct {
	Result               *Result  `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FilterResponse) Reset()         { *m = FilterResponse{} }
func (m *FilterResponse) String() string { return proto.CompactTextString(m) }
func (*FilterResponse) ProtoMessage()    {}
func (*FilterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{9}
}

func (m *FilterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilterResponse.Unmarshal(m, b)
}
func (m *FilterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilterResponse.Marshal(b, m, deterministic)
}
func (m *FilterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilterResponse.Merge(m, src)
}
func (m *FilterResponse) XXX_Size() int {
	return xxx_messageInfo_FilterResponse.Size(m)
}
func (m *FilterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FilterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FilterResponse proto.InternalMessageInfo

func (m *FilterResponse) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

type MetaRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MetaRequest) Reset()         { *m = MetaRequest{} }
func (m *MetaRequest) String() string { return proto.CompactTextString(m) }
func (*MetaRequest) ProtoMessage()    {}
func (*MetaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{10}
}

func (m *MetaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetaRequest.Unmarshal(m, b)
}
func (m *MetaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetaRequest.Marshal(b, m, deterministic)
}
func (m *MetaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetaRequest.Merge(m, src)
}
func (m *MetaRequest) XXX_Size() int {
	return xxx_messageInfo_MetaRequest.Size(m)
}
func (m *MetaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MetaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MetaRequest proto.InternalMessageInfo

type MetaResponse struct {
	Results              map[string]*MetaKeyValue `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *MetaResponse) Reset()         { *m = MetaResponse{} }
func (m *MetaResponse) String() string { return proto.CompactTextString(m) }
func (*MetaResponse) ProtoMessage()    {}
func (*MetaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{11}
}

func (m *MetaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetaResponse.Unmarshal(m, b)
}
func (m *MetaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetaResponse.Marshal(b, m, deterministic)
}
func (m *MetaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetaResponse.Merge(m, src)
}
func (m *MetaResponse) XXX_Size() int {
	return xxx_messageInfo_MetaResponse.Size(m)
}
func (m *MetaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MetaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MetaResponse proto.InternalMessageInfo

func (m *MetaResponse) GetResults() map[string]*MetaKeyValue {
	if m != nil {
		return m.Results
	}
	return nil
}

type MetaKeyValue struct {
	Keyvalues            map[string]string `protobuf:"bytes,1,rep,name=keyvalues,proto3" json:"keyvalues,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *MetaKeyValue) Reset()         { *m = MetaKeyValue{} }
func (m *MetaKeyValue) String() string { return proto.CompactTextString(m) }
func (*MetaKeyValue) ProtoMessage()    {}
func (*MetaKeyValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{12}
}

func (m *MetaKeyValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetaKeyValue.Unmarshal(m, b)
}
func (m *MetaKeyValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetaKeyValue.Marshal(b, m, deterministic)
}
func (m *MetaKeyValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetaKeyValue.Merge(m, src)
}
func (m *MetaKeyValue) XXX_Size() int {
	return xxx_messageInfo_MetaKeyValue.Size(m)
}
func (m *MetaKeyValue) XXX_DiscardUnknown() {
	xxx_messageInfo_MetaKeyValue.DiscardUnknown(m)
}

var xxx_messageInfo_MetaKeyValue proto.InternalMessageInfo

func (m *MetaKeyValue) GetKeyvalues() map[string]string {
	if m != nil {
		return m.Keyvalues
	}
	return nil
}

type ListGenomesRequest struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListGenomesRequest) Reset()         { *m = ListGenomesRequest{} }
func (m *ListGenomesRequest) String() string { return proto.CompactTextString(m) }
func (*ListGenomesRequest) ProtoMessage()    {}
func (*ListGenomesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{13}
}

func (m *ListGenomesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListGenomesRequest.Unmarshal(m, b)
}
func (m *ListGenomesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListGenomesRequest.Marshal(b, m, deterministic)
}
func (m *ListGenomesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListGenomesRequest.Merge(m, src)
}
func (m *ListGenomesRequest) XXX_Size() int {
	return xxx_messageInfo_ListGenomesRequest.Size(m)
}
func (m *ListGenomesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListGenomesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListGenomesRequest proto.InternalMessageInfo

func (m *ListGenomesRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type ListGenomesResponse struct {
	Results              string   `protobuf:"bytes,1,opt,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListGenomesResponse) Reset()         { *m = ListGenomesResponse{} }
func (m *ListGenomesResponse) String() string { return proto.CompactTextString(m) }
func (*ListGenomesResponse) ProtoMessage()    {}
func (*ListGenomesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{14}
}

func (m *ListGenomesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListGenomesResponse.Unmarshal(m, b)
}
func (m *ListGenomesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListGenomesResponse.Marshal(b, m, deterministic)
}
func (m *ListGenomesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListGenomesResponse.Merge(m, src)
}
func (m *ListGenomesResponse) XXX_Size() int {
	return xxx_messageInfo_ListGenomesResponse.Size(m)
}
func (m *ListGenomesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListGenomesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListGenomesResponse proto.InternalMessageInfo

func (m *ListGenomesResponse) GetResults() string {
	if m != nil {
		return m.Results
	}
	return ""
}

type Result struct {
	Results  []*Xref `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Nextpage string  `protobuf:"bytes,2,opt,name=nextpage,proto3" json:"nextpage,omitempty"`
	Message  string  `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// Full mode enhancements (transient - populated at response time)
	Query                *SearchQueryInfo `protobuf:"bytes,4,opt,name=query,proto3" json:"query,omitempty"`
	Stats                *SearchStats     `protobuf:"bytes,5,opt,name=stats,proto3" json:"stats,omitempty"`
	Pagination           *PaginationInfo  `protobuf:"bytes,6,opt,name=pagination,proto3" json:"pagination,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{15}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetResults() []*Xref {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *Result) GetNextpage() string {
	if m != nil {
		return m.Nextpage
	}
	return ""
}

func (m *Result) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Result) GetQuery() *SearchQueryInfo {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *Result) GetStats() *SearchStats {
	if m != nil {
		return m.Stats
	}
	return nil
}

func (m *Result) GetPagination() *PaginationInfo {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type MapFilterResult struct {
	Results  []*MapFilter `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Nextpage string       `protobuf:"bytes,2,opt,name=nextpage,proto3" json:"nextpage,omitempty"`
	Message  string       `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// Full mode enhancements (transient - populated at response time)
	Query                *MapFilterQueryInfo `protobuf:"bytes,4,opt,name=query,proto3" json:"query,omitempty"`
	Stats                *MapFilterStats     `protobuf:"bytes,5,opt,name=stats,proto3" json:"stats,omitempty"`
	Pagination           *PaginationInfo     `protobuf:"bytes,6,opt,name=pagination,proto3" json:"pagination,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *MapFilterResult) Reset()         { *m = MapFilterResult{} }
func (m *MapFilterResult) String() string { return proto.CompactTextString(m) }
func (*MapFilterResult) ProtoMessage()    {}
func (*MapFilterResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{16}
}

func (m *MapFilterResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MapFilterResult.Unmarshal(m, b)
}
func (m *MapFilterResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MapFilterResult.Marshal(b, m, deterministic)
}
func (m *MapFilterResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MapFilterResult.Merge(m, src)
}
func (m *MapFilterResult) XXX_Size() int {
	return xxx_messageInfo_MapFilterResult.Size(m)
}
func (m *MapFilterResult) XXX_DiscardUnknown() {
	xxx_messageInfo_MapFilterResult.DiscardUnknown(m)
}

var xxx_messageInfo_MapFilterResult proto.InternalMessageInfo

func (m *MapFilterResult) GetResults() []*MapFilter {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *MapFilterResult) GetNextpage() string {
	if m != nil {
		return m.Nextpage
	}
	return ""
}

func (m *MapFilterResult) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *MapFilterResult) GetQuery() *MapFilterQueryInfo {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *MapFilterResult) GetStats() *MapFilterStats {
	if m != nil {
		return m.Stats
	}
	return nil
}

func (m *MapFilterResult) GetPagination() *PaginationInfo {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type MapFilter struct {
	Source               *Xref    `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Targets              []*Xref  `protobuf:"bytes,2,rep,name=targets,proto3" json:"targets,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MapFilter) Reset()         { *m = MapFilter{} }
func (m *MapFilter) String() string { return proto.CompactTextString(m) }
func (*MapFilter) ProtoMessage()    {}
func (*MapFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{17}
}

func (m *MapFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MapFilter.Unmarshal(m, b)
}
func (m *MapFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MapFilter.Marshal(b, m, deterministic)
}
func (m *MapFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MapFilter.Merge(m, src)
}
func (m *MapFilter) XXX_Size() int {
	return xxx_messageInfo_MapFilter.Size(m)
}
func (m *MapFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_MapFilter.DiscardUnknown(m)
}

var xxx_messageInfo_MapFilter proto.InternalMessageInfo

func (m *MapFilter) GetSource() *Xref {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *MapFilter) GetTargets() []*Xref {
	if m != nil {
		return m.Targets
	}
	return nil
}

type Xref struct {
	Dataset     uint32 `protobuf:"varint,1,opt,name=dataset,proto3" json:"dataset,omitempty"`
	DatasetName string `protobuf:"bytes,31,opt,name=dataset_name,json=datasetName,proto3" json:"dataset_name,omitempty"`
	IsLink      bool   `protobuf:"varint,2,opt,name=is_link,json=isLink,proto3" json:"is_link,omitempty"`
	Identifier  string `protobuf:"bytes,3,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Keyword     string `protobuf:"bytes,4,opt,name=keyword,proto3" json:"keyword,omitempty"`
	// Types that are valid to be assigned to Attributes:
	//
	//	*Xref_Empty
	//	*Xref_Uniprot
	//	*Xref_Ontology
	//	*Xref_Hgnc
	//	*Xref_Interpro
	//	*Xref_Ensembl
	//	*Xref_Taxonomy
	//	*Xref_Hmdb
	//	*Xref_Chebi
	//	*Xref_Ena
	//	*Xref_Pdb
	//	*Xref_Drugbank
	//	*Xref_Orphanet
	//	*Xref_Reactome
	//	*Xref_Chembl
	//	*Xref_Ufeature
	//	*Xref_Patent
	//	*Xref_ClinicalTrials
	//	*Xref_Stringattr
	//	*Xref_Alphafold
	//	*Xref_Rnacentral
	//	*Xref_Clinvar
	//	*Xref_Lipidmaps
	//	*Xref_Swisslipids
	//	*Xref_Bgee
	//	*Xref_Rhea
	//	*Xref_GwasStudy
	//	*Xref_Gwas
	//	*Xref_Intact
	//	*Xref_ProteinSimilarity
	//	*Xref_Antibody
	//	*Xref_Pubchem
	//	*Xref_PubchemActivity
	//	*Xref_PubchemAssay
	//	*Xref_Dbsnp
	//	*Xref_Mesh
	//	*Xref_Entrez
	//	*Xref_Refseq
	//	*Xref_Gencc
	Attributes           isXref_Attributes    `protobuf_oneof:"attributes"`
	Count                uint32               `protobuf:"varint,20,opt,name=count,proto3" json:"count,omitempty"`
	Entries              []*XrefEntry         `protobuf:"bytes,21,rep,name=entries,proto3" json:"entries,omitempty"`
	DatasetCounts        []*XrefDomainCount   `protobuf:"bytes,22,rep,name=dataset_counts,json=datasetCounts,proto3" json:"dataset_counts,omitempty"`
	DatasetPages         map[uint32]*PageInfo `protobuf:"bytes,23,rep,name=datasetPages,proto3" json:"datasetPages,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Pages                []string             `protobuf:"bytes,24,rep,name=pages,proto3" json:"pages,omitempty"`
	Url                  string               `protobuf:"bytes,25,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Xref) Reset()         { *m = Xref{} }
func (m *Xref) String() string { return proto.CompactTextString(m) }
func (*Xref) ProtoMessage()    {}
func (*Xref) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{18}
}

func (m *Xref) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Xref.Unmarshal(m, b)
}
func (m *Xref) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Xref.Marshal(b, m, deterministic)
}
func (m *Xref) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Xref.Merge(m, src)
}
func (m *Xref) XXX_Size() int {
	return xxx_messageInfo_Xref.Size(m)
}
func (m *Xref) XXX_DiscardUnknown() {
	xxx_messageInfo_Xref.DiscardUnknown(m)
}

var xxx_messageInfo_Xref proto.InternalMessageInfo

func (m *Xref) GetDataset() uint32 {
	if m != nil {
		return m.Dataset
	}
	return 0
}

func (m *Xref) GetDatasetName() string {
	if m != nil {
		return m.DatasetName
	}
	return ""
}

func (m *Xref) GetIsLink() bool {
	if m != nil {
		return m.IsLink
	}
	return false
}

func (m *Xref) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *Xref) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

type isXref_Attributes interface {
	isXref_Attributes()
}

type Xref_Empty struct {
	Empty bool `protobuf:"varint,5,opt,name=empty,proto3,oneof"`
}

type Xref_Uniprot struct {
	Uniprot *UniprotAttr `protobuf:"bytes,6,opt,name=uniprot,proto3,oneof"`
}

type Xref_Ontology struct {
	Ontology *OntologyAttr `protobuf:"bytes,7,opt,name=ontology,proto3,oneof"`
}

type Xref_Hgnc struct {
	Hgnc *HgncAttr `protobuf:"bytes,8,opt,name=hgnc,proto3,oneof"`
}

type Xref_Interpro struct {
	Interpro *InterproAttr `protobuf:"bytes,9,opt,name=interpro,proto3,oneof"`
}

type Xref_Ensembl struct {
	Ensembl *EnsemblAttr `protobuf:"bytes,10,opt,name=ensembl,proto3,oneof"`
}

type Xref_Taxonomy struct {
	Taxonomy *TaxoAttr `protobuf:"bytes,11,opt,name=taxonomy,proto3,oneof"`
}

type Xref_Hmdb struct {
	Hmdb *HmdbAttr `protobuf:"bytes,12,opt,name=hmdb,proto3,oneof"`
}

type Xref_Chebi struct {
	Chebi *ChebiAttr `protobuf:"bytes,32,opt,name=chebi,proto3,oneof"`
}

type Xref_Ena struct {
	Ena *EnaAttr `protobuf:"bytes,13,opt,name=ena,proto3,oneof"`
}

type Xref_Pdb struct {
	Pdb *PdbAttr `protobuf:"bytes,14,opt,name=pdb,proto3,oneof"`
}

type Xref_Drugbank struct {
	Drugbank *DrugbankAttr `protobuf:"bytes,15,opt,name=drugbank,proto3,oneof"`
}

type Xref_Orphanet struct {
	Orphanet *OrphanetAttr `protobuf:"bytes,16,opt,name=orphanet,proto3,oneof"`
}

type Xref_Reactome struct {
	Reactome *ReactomePathwayAttr `protobuf:"bytes,17,opt,name=reactome,proto3,oneof"`
}

type Xref_Chembl struct {
	Chembl *ChemblAttr `protobuf:"bytes,18,opt,name=chembl,proto3,oneof"`
}

type Xref_Ufeature struct {
	Ufeature *UniprotFeatureAttr `protobuf:"bytes,19,opt,name=ufeature,proto3,oneof"`
}

type Xref_Patent struct {
	Patent *PatentAttr `protobuf:"bytes,26,opt,name=patent,proto3,oneof"`
}

type Xref_ClinicalTrials struct {
	ClinicalTrials *ClinicalTrialAttr `protobuf:"bytes,27,opt,name=clinical_trials,json=clinicalTrials,proto3,oneof"`
}

type Xref_Stringattr struct {
	Stringattr *StringAttr `protobuf:"bytes,28,opt,name=stringattr,proto3,oneof"`
}

type Xref_Alphafold struct {
	Alphafold *AlphaFoldAttr `protobuf:"bytes,29,opt,name=alphafold,proto3,oneof"`
}

type Xref_Rnacentral struct {
	Rnacentral *RnacentralAttr `protobuf:"bytes,30,opt,name=rnacentral,proto3,oneof"`
}

type Xref_Clinvar struct {
	Clinvar *ClinvarAttr `protobuf:"bytes,33,opt,name=clinvar,proto3,oneof"`
}

type Xref_Lipidmaps struct {
	Lipidmaps *LipidmapsAttr `protobuf:"bytes,34,opt,name=lipidmaps,proto3,oneof"`
}

type Xref_Swisslipids struct {
	Swisslipids *SwisslipidsAttr `protobuf:"bytes,35,opt,name=swisslipids,proto3,oneof"`
}

type Xref_Bgee struct {
	Bgee *BgeeAttr `protobuf:"bytes,36,opt,name=bgee,proto3,oneof"`
}

type Xref_Rhea struct {
	Rhea *RheaAttr `protobuf:"bytes,38,opt,name=rhea,proto3,oneof"`
}

type Xref_GwasStudy struct {
	GwasStudy *GwasStudyAttr `protobuf:"bytes,39,opt,name=gwas_study,json=gwasStudy,proto3,oneof"`
}

type Xref_Gwas struct {
	Gwas *GwasAttr `protobuf:"bytes,43,opt,name=gwas,proto3,oneof"`
}

type Xref_Intact struct {
	Intact *IntactAttr `protobuf:"bytes,44,opt,name=intact,proto3,oneof"`
}

type Xref_ProteinSimilarity struct {
	ProteinSimilarity *ProteinSimilarityAttr `protobuf:"bytes,45,opt,name=protein_similarity,json=proteinSimilarity,proto3,oneof"`
}

type Xref_Antibody struct {
	Antibody *AntibodyAttr `protobuf:"bytes,46,opt,name=antibody,proto3,oneof"`
}

type Xref_Pubchem struct {
	Pubchem *PubchemAttr `protobuf:"bytes,47,opt,name=pubchem,proto3,oneof"`
}

type Xref_PubchemActivity struct {
	PubchemActivity *PubchemActivityAttr `protobuf:"bytes,48,opt,name=pubchem_activity,json=pubchemActivity,proto3,oneof"`
}

type Xref_PubchemAssay struct {
	PubchemAssay *PubchemAssayAttr `protobuf:"bytes,49,opt,name=pubchem_assay,json=pubchemAssay,proto3,oneof"`
}

type Xref_Dbsnp struct {
	Dbsnp *DbsnpAttr `protobuf:"bytes,123,opt,name=dbsnp,proto3,oneof"`
}

type Xref_Mesh struct {
	Mesh *MeshAttr `protobuf:"bytes,50,opt,name=mesh,proto3,oneof"`
}

type Xref_Entrez struct {
	Entrez *EntrezAttr `protobuf:"bytes,53,opt,name=entrez,proto3,oneof"`
}

type Xref_Refseq struct {
	Refseq *RefSeqAttr `protobuf:"bytes,57,opt,name=refseq,proto3,oneof"`
}

type Xref_Gencc struct {
	Gencc *GenccAttr `protobuf:"bytes,58,opt,name=gencc,proto3,oneof"`
}

func (*Xref_Empty) isXref_Attributes() {}

func (*Xref_Uniprot) isXref_Attributes() {}

func (*Xref_Ontology) isXref_Attributes() {}

func (*Xref_Hgnc) isXref_Attributes() {}

func (*Xref_Interpro) isXref_Attributes() {}

func (*Xref_Ensembl) isXref_Attributes() {}

func (*Xref_Taxonomy) isXref_Attributes() {}

func (*Xref_Hmdb) isXref_Attributes() {}

func (*Xref_Chebi) isXref_Attributes() {}

func (*Xref_Ena) isXref_Attributes() {}

func (*Xref_Pdb) isXref_Attributes() {}

func (*Xref_Drugbank) isXref_Attributes() {}

func (*Xref_Orphanet) isXref_Attributes() {}

func (*Xref_Reactome) isXref_Attributes() {}

func (*Xref_Chembl) isXref_Attributes() {}

func (*Xref_Ufeature) isXref_Attributes() {}

func (*Xref_Patent) isXref_Attributes() {}

func (*Xref_ClinicalTrials) isXref_Attributes() {}

func (*Xref_Stringattr) isXref_Attributes() {}

func (*Xref_Alphafold) isXref_Attributes() {}

func (*Xref_Rnacentral) isXref_Attributes() {}

func (*Xref_Clinvar) isXref_Attributes() {}

func (*Xref_Lipidmaps) isXref_Attributes() {}

func (*Xref_Swisslipids) isXref_Attributes() {}

func (*Xref_Bgee) isXref_Attributes() {}

func (*Xref_Rhea) isXref_Attributes() {}

func (*Xref_GwasStudy) isXref_Attributes() {}

func (*Xref_Gwas) isXref_Attributes() {}

func (*Xref_Intact) isXref_Attributes() {}

func (*Xref_ProteinSimilarity) isXref_Attributes() {}

func (*Xref_Antibody) isXref_Attributes() {}

func (*Xref_Pubchem) isXref_Attributes() {}

func (*Xref_PubchemActivity) isXref_Attributes() {}

func (*Xref_PubchemAssay) isXref_Attributes() {}

func (*Xref_Dbsnp) isXref_Attributes() {}

func (*Xref_Mesh) isXref_Attributes() {}

func (*Xref_Entrez) isXref_Attributes() {}

func (*Xref_Refseq) isXref_Attributes() {}

func (*Xref_Gencc) isXref_Attributes() {}

func (m *Xref) GetAttributes() isXref_Attributes {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *Xref) GetEmpty() bool {
	if x, ok := m.GetAttributes().(*Xref_Empty); ok {
		return x.Empty
	}
	return false
}

func (m *Xref) GetUniprot() *UniprotAttr {
	if x, ok := m.GetAttributes().(*Xref_Uniprot); ok {
		return x.Uniprot
	}
	return nil
}

func (m *Xref) GetOntology() *OntologyAttr {
	if x, ok := m.GetAttributes().(*Xref_Ontology); ok {
		return x.Ontology
	}
	return nil
}

func (m *Xref) GetHgnc() *HgncAttr {
	if x, ok := m.GetAttributes().(*Xref_Hgnc); ok {
		return x.Hgnc
	}
	return nil
}

func (m *Xref) GetInterpro() *InterproAttr {
	if x, ok := m.GetAttributes().(*Xref_Interpro); ok {
		return x.Interpro
	}
	return nil
}

func (m *Xref) GetEnsembl() *EnsemblAttr {
	if x, ok := m.GetAttributes().(*Xref_Ensembl); ok {
		return x.Ensembl
	}
	return nil
}

func (m *Xref) GetTaxonomy() *TaxoAttr {
	if x, ok := m.GetAttributes().(*Xref_Taxonomy); ok {
		return x.Taxonomy
	}
	return nil
}

func (m *Xref) GetHmdb() *HmdbAttr {
	if x, ok := m.GetAttributes().(*Xref_Hmdb); ok {
		return x.Hmdb
	}
	return nil
}

func (m *Xref) GetChebi() *ChebiAttr {
	if x, ok := m.GetAttributes().(*Xref_Chebi); ok {
		return x.Chebi
	}
	return nil
}

func (m *Xref) GetEna() *EnaAttr {
	if x, ok := m.GetAttributes().(*Xref_Ena); ok {
		return x.Ena
	}
	return nil
}

func (m *Xref) GetPdb() *PdbAttr {
	if x, ok := m.GetAttributes().(*Xref_Pdb); ok {
		return x.Pdb
	}
	return nil
}

func (m *Xref) GetDrugbank() *DrugbankAttr {
	if x, ok := m.GetAttributes().(*Xref_Drugbank); ok {
		return x.Drugbank
	}
	return nil
}

func (m *Xref) GetOrphanet() *OrphanetAttr {
	if x, ok := m.GetAttributes().(*Xref_Orphanet); ok {
		return x.Orphanet
	}
	return nil
}

func (m *Xref) GetReactome() *ReactomePathwayAttr {
	if x, ok := m.GetAttributes().(*Xref_Reactome); ok {
		return x.Reactome
	}
	return nil
}

func (m *Xref) GetChembl() *ChemblAttr {
	if x, ok := m.GetAttributes().(*Xref_Chembl); ok {
		return x.Chembl
	}
	return nil
}

func (m *Xref) GetUfeature() *UniprotFeatureAttr {
	if x, ok := m.GetAttributes().(*Xref_Ufeature); ok {
		return x.Ufeature
	}
	return nil
}

func (m *Xref) GetPatent() *PatentAttr {
	if x, ok := m.GetAttributes().(*Xref_Patent); ok {
		return x.Patent
	}
	return nil
}

func (m *Xref) GetClinicalTrials() *ClinicalTrialAttr {
	if x, ok := m.GetAttributes().(*Xref_ClinicalTrials); ok {
		return x.ClinicalTrials
	}
	return nil
}

func (m *Xref) GetStringattr() *StringAttr {
	if x, ok := m.GetAttributes().(*Xref_Stringattr); ok {
		return x.Stringattr
	}
	return nil
}

func (m *Xref) GetAlphafold() *AlphaFoldAttr {
	if x, ok := m.GetAttributes().(*Xref_Alphafold); ok {
		return x.Alphafold
	}
	return nil
}

func (m *Xref) GetRnacentral() *RnacentralAttr {
	if x, ok := m.GetAttributes().(*Xref_Rnacentral); ok {
		return x.Rnacentral
	}
	return nil
}

func (m *Xref) GetClinvar() *ClinvarAttr {
	if x, ok := m.GetAttributes().(*Xref_Clinvar); ok {
		return x.Clinvar
	}
	return nil
}

func (m *Xref) GetLipidmaps() *LipidmapsAttr {
	if x, ok := m.GetAttributes().(*Xref_Lipidmaps); ok {
		return x.Lipidmaps
	}
	return nil
}

func (m *Xref) GetSwisslipids() *SwisslipidsAttr {
	if x, ok := m.GetAttributes().(*Xref_Swisslipids); ok {
		return x.Swisslipids
	}
	return nil
}

func (m *Xref) GetBgee() *BgeeAttr {
	if x, ok := m.GetAttributes().(*Xref_Bgee); ok {
		return x.Bgee
	}
	return nil
}

func (m *Xref) GetRhea() *RheaAttr {
	if x, ok := m.GetAttributes().(*Xref_Rhea); ok {
		return x.Rhea
	}
	return nil
}

func (m *Xref) GetGwasStudy() *GwasStudyAttr {
	if x, ok := m.GetAttributes().(*Xref_GwasStudy); ok {
		return x.GwasStudy
	}
	return nil
}

func (m *Xref) GetGwas() *GwasAttr {
	if x, ok := m.GetAttributes().(*Xref_Gwas); ok {
		return x.Gwas
	}
	return nil
}

func (m *Xref) GetIntact() *IntactAttr {
	if x, ok := m.GetAttributes().(*Xref_Intact); ok {
		return x.Intact
	}
	return nil
}

func (m *Xref) GetProteinSimilarity() *ProteinSimilarityAttr {
	if x, ok := m.GetAttributes().(*Xref_ProteinSimilarity); ok {
		return x.ProteinSimilarity
	}
	return nil
}

func (m *Xref) GetAntibody() *AntibodyAttr {
	if x, ok := m.GetAttributes().(*Xref_Antibody); ok {
		return x.Antibody
	}
	return nil
}

func (m *Xref) GetPubchem() *PubchemAttr {
	if x, ok := m.GetAttributes().(*Xref_Pubchem); ok {
		return x.Pubchem
	}
	return nil
}

func (m *Xref) GetPubchemActivity() *PubchemActivityAttr {
	if x, ok := m.GetAttributes().(*Xref_PubchemActivity); ok {
		return x.PubchemActivity
	}
	return nil
}

func (m *Xref) GetPubchemAssay() *PubchemAssayAttr {
	if x, ok := m.GetAttributes().(*Xref_PubchemAssay); ok {
		return x.PubchemAssay
	}
	return nil
}

func (m *Xref) GetDbsnp() *DbsnpAttr {
	if x, ok := m.GetAttributes().(*Xref_Dbsnp); ok {
		return x.Dbsnp
	}
	return nil
}

func (m *Xref) GetMesh() *MeshAttr {
	if x, ok := m.GetAttributes().(*Xref_Mesh); ok {
		return x.Mesh
	}
	return nil
}

func (m *Xref) GetEntrez() *EntrezAttr {
	if x, ok := m.GetAttributes().(*Xref_Entrez); ok {
		return x.Entrez
	}
	return nil
}

func (m *Xref) GetRefseq() *RefSeqAttr {
	if x, ok := m.GetAttributes().(*Xref_Refseq); ok {
		return x.Refseq
	}
	return nil
}

func (m *Xref) GetGencc() *GenccAttr {
	if x, ok := m.GetAttributes().(*Xref_Gencc); ok {
		return x.Gencc
	}
	return nil
}

func (m *Xref) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *Xref) GetEntries() []*XrefEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

func (m *Xref) GetDatasetCounts() []*XrefDomainCount {
	if m != nil {
		return m.DatasetCounts
	}
	return nil
}

func (m *Xref) GetDatasetPages() map[uint32]*PageInfo {
	if m != nil {
		return m.DatasetPages
	}
	return nil
}

func (m *Xref) GetPages() []string {
	if m != nil {
		return m.Pages
	}
	return nil
}

func (m *Xref) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Xref) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Xref_Empty)(nil),
		(*Xref_Uniprot)(nil),
		(*Xref_Ontology)(nil),
		(*Xref_Hgnc)(nil),
		(*Xref_Interpro)(nil),
		(*Xref_Ensembl)(nil),
		(*Xref_Taxonomy)(nil),
		(*Xref_Hmdb)(nil),
		(*Xref_Chebi)(nil),
		(*Xref_Ena)(nil),
		(*Xref_Pdb)(nil),
		(*Xref_Drugbank)(nil),
		(*Xref_Orphanet)(nil),
		(*Xref_Reactome)(nil),
		(*Xref_Chembl)(nil),
		(*Xref_Ufeature)(nil),
		(*Xref_Patent)(nil),
		(*Xref_ClinicalTrials)(nil),
		(*Xref_Stringattr)(nil),
		(*Xref_Alphafold)(nil),
		(*Xref_Rnacentral)(nil),
		(*Xref_Clinvar)(nil),
		(*Xref_Lipidmaps)(nil),
		(*Xref_Swisslipids)(nil),
		(*Xref_Bgee)(nil),
		(*Xref_Rhea)(nil),
		(*Xref_GwasStudy)(nil),
		(*Xref_Gwas)(nil),
		(*Xref_Intact)(nil),
		(*Xref_ProteinSimilarity)(nil),
		(*Xref_Antibody)(nil),
		(*Xref_Pubchem)(nil),
		(*Xref_PubchemActivity)(nil),
		(*Xref_PubchemAssay)(nil),
		(*Xref_Dbsnp)(nil),
		(*Xref_Mesh)(nil),
		(*Xref_Entrez)(nil),
		(*Xref_Refseq)(nil),
		(*Xref_Gencc)(nil),
	}
}

type PageInfo struct {
	Pages                []string `protobuf:"bytes,1,rep,name=pages,proto3" json:"pages,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PageInfo) Reset()         { *m = PageInfo{} }
func (m *PageInfo) String() string { return proto.CompactTextString(m) }
func (*PageInfo) ProtoMessage()    {}
func (*PageInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{19}
}

func (m *PageInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageInfo.Unmarshal(m, b)
}
func (m *PageInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageInfo.Marshal(b, m, deterministic)
}
func (m *PageInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageInfo.Merge(m, src)
}
func (m *PageInfo) XXX_Size() int {
	return xxx_messageInfo_PageInfo.Size(m)
}
func (m *PageInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PageInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PageInfo proto.InternalMessageInfo

func (m *PageInfo) GetPages() []string {
	if m != nil {
		return m.Pages
	}
	return nil
}

type XrefEntry struct {
	Dataset     uint32 `protobuf:"varint,1,opt,name=dataset,proto3" json:"dataset,omitempty"`
	DatasetName string `protobuf:"bytes,4,opt,name=dataset_name,json=datasetName,proto3" json:"dataset_name,omitempty"`
	Identifier  string `protobuf:"bytes,2,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Evidence    string `protobuf:"bytes,3,opt,name=evidence,proto3" json:"evidence,omitempty"`
	// TAS = Traceable Author Statement (manually curated)
	// IEA = Inferred by Electronic Annotation (computationally inferred)
	Relationship         string   `protobuf:"bytes,5,opt,name=relationship,proto3" json:"relationship,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *XrefEntry) Reset()         { *m = XrefEntry{} }
func (m *XrefEntry) String() string { return proto.CompactTextString(m) }
func (*XrefEntry) ProtoMessage()    {}
func (*XrefEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{20}
}

func (m *XrefEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XrefEntry.Unmarshal(m, b)
}
func (m *XrefEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XrefEntry.Marshal(b, m, deterministic)
}
func (m *XrefEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XrefEntry.Merge(m, src)
}
func (m *XrefEntry) XXX_Size() int {
	return xxx_messageInfo_XrefEntry.Size(m)
}
func (m *XrefEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_XrefEntry.DiscardUnknown(m)
}

var xxx_messageInfo_XrefEntry proto.InternalMessageInfo

func (m *XrefEntry) GetDataset() uint32 {
	if m != nil {
		return m.Dataset
	}
	return 0
}

func (m *XrefEntry) GetDatasetName() string {
	if m != nil {
		return m.DatasetName
	}
	return ""
}

func (m *XrefEntry) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *XrefEntry) GetEvidence() string {
	if m != nil {
		return m.Evidence
	}
	return ""
}

func (m *XrefEntry) GetRelationship() string {
	if m != nil {
		return m.Relationship
	}
	return ""
}

type XrefDomainCount struct {
	Dataset              uint32   `protobuf:"varint,1,opt,name=dataset,proto3" json:"dataset,omitempty"`
	Count                uint32   `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *XrefDomainCount) Reset()         { *m = XrefDomainCount{} }
func (m *XrefDomainCount) String() string { return proto.CompactTextString(m) }
func (*XrefDomainCount) ProtoMessage()    {}
func (*XrefDomainCount) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{21}
}

func (m *XrefDomainCount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XrefDomainCount.Unmarshal(m, b)
}
func (m *XrefDomainCount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XrefDomainCount.Marshal(b, m, deterministic)
}
func (m *XrefDomainCount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XrefDomainCount.Merge(m, src)
}
func (m *XrefDomainCount) XXX_Size() int {
	return xxx_messageInfo_XrefDomainCount.Size(m)
}
func (m *XrefDomainCount) XXX_DiscardUnknown() {
	xxx_messageInfo_XrefDomainCount.DiscardUnknown(m)
}

var xxx_messageInfo_XrefDomainCount proto.InternalMessageInfo

func (m *XrefDomainCount) GetDataset() uint32 {
	if m != nil {
		return m.Dataset
	}
	return 0
}

func (m *XrefDomainCount) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type Alias struct {
	Identifiers          []string `protobuf:"bytes,1,rep,name=identifiers,proto3" json:"identifiers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Alias) Reset()         { *m = Alias{} }
func (m *Alias) String() string { return proto.CompactTextString(m) }
func (*Alias) ProtoMessage()    {}
func (*Alias) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{22}
}

func (m *Alias) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Alias.Unmarshal(m, b)
}
func (m *Alias) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Alias.Marshal(b, m, deterministic)
}
func (m *Alias) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Alias.Merge(m, src)
}
func (m *Alias) XXX_Size() int {
	return xxx_messageInfo_Alias.Size(m)
}
func (m *Alias) XXX_DiscardUnknown() {
	xxx_messageInfo_Alias.DiscardUnknown(m)
}

var xxx_messageInfo_Alias proto.InternalMessageInfo

func (m *Alias) GetIdentifiers() []string {
	if m != nil {
		return m.Identifiers
	}
	return nil
}

// Lite mode response for mapping queries
type MapFilterResultLite struct {
	Mode                 string              `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	Query                *MapFilterQueryInfo `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Mappings             []*MapFilterLite    `protobuf:"bytes,3,rep,name=mappings,proto3" json:"mappings,omitempty"`
	Stats                *MapFilterStats     `protobuf:"bytes,4,opt,name=stats,proto3" json:"stats,omitempty"`
	Pagination           *PaginationInfo     `protobuf:"bytes,5,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Warnings             []string            `protobuf:"bytes,6,rep,name=warnings,proto3" json:"warnings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *MapFilterResultLite) Reset()         { *m = MapFilterResultLite{} }
func (m *MapFilterResultLite) String() string { return proto.CompactTextString(m) }
func (*MapFilterResultLite) ProtoMessage()    {}
func (*MapFilterResultLite) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{23}
}

func (m *MapFilterResultLite) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MapFilterResultLite.Unmarshal(m, b)
}
func (m *MapFilterResultLite) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MapFilterResultLite.Marshal(b, m, deterministic)
}
func (m *MapFilterResultLite) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MapFilterResultLite.Merge(m, src)
}
func (m *MapFilterResultLite) XXX_Size() int {
	return xxx_messageInfo_MapFilterResultLite.Size(m)
}
func (m *MapFilterResultLite) XXX_DiscardUnknown() {
	xxx_messageInfo_MapFilterResultLite.DiscardUnknown(m)
}

var xxx_messageInfo_MapFilterResultLite proto.InternalMessageInfo

func (m *MapFilterResultLite) GetMode() string {
	if m != nil {
		return m.Mode
	}
	return ""
}

func (m *MapFilterResultLite) GetQuery() *MapFilterQueryInfo {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *MapFilterResultLite) GetMappings() []*MapFilterLite {
	if m != nil {
		return m.Mappings
	}
	return nil
}

func (m *MapFilterResultLite) GetStats() *MapFilterStats {
	if m != nil {
		return m.Stats
	}
	return nil
}

func (m *MapFilterResultLite) GetPagination() *PaginationInfo {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func (m *MapFilterResultLite) GetWarnings() []string {
	if m != nil {
		return m.Warnings
	}
	return nil
}

type MapFilterLite struct {
	Input                string       `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	Source               *LiteEntry   `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Targets              []*LiteEntry `protobuf:"bytes,3,rep,name=targets,proto3" json:"targets,omitempty"`
	Error                string       `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *MapFilterLite) Reset()         { *m = MapFilterLite{} }
func (m *MapFilterLite) String() string { return proto.CompactTextString(m) }
func (*MapFilterLite) ProtoMessage()    {}
func (*MapFilterLite) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{24}
}

func (m *MapFilterLite) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MapFilterLite.Unmarshal(m, b)
}
func (m *MapFilterLite) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MapFilterLite.Marshal(b, m, deterministic)
}
func (m *MapFilterLite) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MapFilterLite.Merge(m, src)
}
func (m *MapFilterLite) XXX_Size() int {
	return xxx_messageInfo_MapFilterLite.Size(m)
}
func (m *MapFilterLite) XXX_DiscardUnknown() {
	xxx_messageInfo_MapFilterLite.DiscardUnknown(m)
}

var xxx_messageInfo_MapFilterLite proto.InternalMessageInfo

func (m *MapFilterLite) GetInput() string {
	if m != nil {
		return m.Input
	}
	return ""
}

func (m *MapFilterLite) GetSource() *LiteEntry {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *MapFilterLite) GetTargets() []*LiteEntry {
	if m != nil {
		return m.Targets
	}
	return nil
}

func (m *MapFilterLite) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type LiteEntry struct {
	D                    string   `protobuf:"bytes,1,opt,name=d,proto3" json:"d,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	HasAttr              bool     `protobuf:"varint,3,opt,name=has_attr,json=hasAttr,proto3" json:"has_attr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LiteEntry) Reset()         { *m = LiteEntry{} }
func (m *LiteEntry) String() string { return proto.CompactTextString(m) }
func (*LiteEntry) ProtoMessage()    {}
func (*LiteEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{25}
}

func (m *LiteEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LiteEntry.Unmarshal(m, b)
}
func (m *LiteEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LiteEntry.Marshal(b, m, deterministic)
}
func (m *LiteEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LiteEntry.Merge(m, src)
}
func (m *LiteEntry) XXX_Size() int {
	return xxx_messageInfo_LiteEntry.Size(m)
}
func (m *LiteEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_LiteEntry.DiscardUnknown(m)
}

var xxx_messageInfo_LiteEntry proto.InternalMessageInfo

func (m *LiteEntry) GetD() string {
	if m != nil {
		return m.D
	}
	return ""
}

func (m *LiteEntry) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *LiteEntry) GetHasAttr() bool {
	if m != nil {
		return m.HasAttr
	}
	return false
}

// Lite mode response for search queries
type ResultLite struct {
	Mode                 string              `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	Query                *SearchQueryInfo    `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Results              []*SearchResultLite `protobuf:"bytes,3,rep,name=results,proto3" json:"results,omitempty"`
	Stats                *SearchStats        `protobuf:"bytes,4,opt,name=stats,proto3" json:"stats,omitempty"`
	Pagination           *PaginationInfo     `protobuf:"bytes,5,opt,name=pagination,proto3" json:"pagination,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ResultLite) Reset()         { *m = ResultLite{} }
func (m *ResultLite) String() string { return proto.CompactTextString(m) }
func (*ResultLite) ProtoMessage()    {}
func (*ResultLite) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{26}
}

func (m *ResultLite) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResultLite.Unmarshal(m, b)
}
func (m *ResultLite) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResultLite.Marshal(b, m, deterministic)
}
func (m *ResultLite) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResultLite.Merge(m, src)
}
func (m *ResultLite) XXX_Size() int {
	return xxx_messageInfo_ResultLite.Size(m)
}
func (m *ResultLite) XXX_DiscardUnknown() {
	xxx_messageInfo_ResultLite.DiscardUnknown(m)
}

var xxx_messageInfo_ResultLite proto.InternalMessageInfo

func (m *ResultLite) GetMode() string {
	if m != nil {
		return m.Mode
	}
	return ""
}

func (m *ResultLite) GetQuery() *SearchQueryInfo {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *ResultLite) GetResults() []*SearchResultLite {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *ResultLite) GetStats() *SearchStats {
	if m != nil {
		return m.Stats
	}
	return nil
}

func (m *ResultLite) GetPagination() *PaginationInfo {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type SearchResultLite struct {
	D                    string   `protobuf:"bytes,1,opt,name=d,proto3" json:"d,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	HasAttr              bool     `protobuf:"varint,3,opt,name=has_attr,json=hasAttr,proto3" json:"has_attr,omitempty"`
	XrefCount            uint32   `protobuf:"varint,4,opt,name=xref_count,json=xrefCount,proto3" json:"xref_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchResultLite) Reset()         { *m = SearchResultLite{} }
func (m *SearchResultLite) String() string { return proto.CompactTextString(m) }
func (*SearchResultLite) ProtoMessage()    {}
func (*SearchResultLite) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{27}
}

func (m *SearchResultLite) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResultLite.Unmarshal(m, b)
}
func (m *SearchResultLite) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResultLite.Marshal(b, m, deterministic)
}
func (m *SearchResultLite) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResultLite.Merge(m, src)
}
func (m *SearchResultLite) XXX_Size() int {
	return xxx_messageInfo_SearchResultLite.Size(m)
}
func (m *SearchResultLite) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResultLite.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResultLite proto.InternalMessageInfo

func (m *SearchResultLite) GetD() string {
	if m != nil {
		return m.D
	}
	return ""
}

func (m *SearchResultLite) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SearchResultLite) GetHasAttr() bool {
	if m != nil {
		return m.HasAttr
	}
	return false
}

func (m *SearchResultLite) GetXrefCount() uint32 {
	if m != nil {
		return m.XrefCount
	}
	return 0
}

type MapFilterQueryInfo struct {
	Terms                []string `protobuf:"bytes,1,rep,name=terms,proto3" json:"terms,omitempty"`
	Chain                string   `protobuf:"bytes,2,opt,name=chain,proto3" json:"chain,omitempty"`
	Raw                  string   `protobuf:"bytes,3,opt,name=raw,proto3" json:"raw,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MapFilterQueryInfo) Reset()         { *m = MapFilterQueryInfo{} }
func (m *MapFilterQueryInfo) String() string { return proto.CompactTextString(m) }
func (*MapFilterQueryInfo) ProtoMessage()    {}
func (*MapFilterQueryInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{28}
}

func (m *MapFilterQueryInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MapFilterQueryInfo.Unmarshal(m, b)
}
func (m *MapFilterQueryInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MapFilterQueryInfo.Marshal(b, m, deterministic)
}
func (m *MapFilterQueryInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MapFilterQueryInfo.Merge(m, src)
}
func (m *MapFilterQueryInfo) XXX_Size() int {
	return xxx_messageInfo_MapFilterQueryInfo.Size(m)
}
func (m *MapFilterQueryInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MapFilterQueryInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MapFilterQueryInfo proto.InternalMessageInfo

func (m *MapFilterQueryInfo) GetTerms() []string {
	if m != nil {
		return m.Terms
	}
	return nil
}

func (m *MapFilterQueryInfo) GetChain() string {
	if m != nil {
		return m.Chain
	}
	return ""
}

func (m *MapFilterQueryInfo) GetRaw() string {
	if m != nil {
		return m.Raw
	}
	return ""
}

type SearchQueryInfo struct {
	Terms                []string `protobuf:"bytes,1,rep,name=terms,proto3" json:"terms,omitempty"`
	DatasetFilter        string   `protobuf:"bytes,2,opt,name=dataset_filter,json=datasetFilter,proto3" json:"dataset_filter,omitempty"`
	Raw                  string   `protobuf:"bytes,3,opt,name=raw,proto3" json:"raw,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchQueryInfo) Reset()         { *m = SearchQueryInfo{} }
func (m *SearchQueryInfo) String() string { return proto.CompactTextString(m) }
func (*SearchQueryInfo) ProtoMessage()    {}
func (*SearchQueryInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{29}
}

func (m *SearchQueryInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchQueryInfo.Unmarshal(m, b)
}
func (m *SearchQueryInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchQueryInfo.Marshal(b, m, deterministic)
}
func (m *SearchQueryInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchQueryInfo.Merge(m, src)
}
func (m *SearchQueryInfo) XXX_Size() int {
	return xxx_messageInfo_SearchQueryInfo.Size(m)
}
func (m *SearchQueryInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchQueryInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SearchQueryInfo proto.InternalMessageInfo

func (m *SearchQueryInfo) GetTerms() []string {
	if m != nil {
		return m.Terms
	}
	return nil
}

func (m *SearchQueryInfo) GetDatasetFilter() string {
	if m != nil {
		return m.DatasetFilter
	}
	return ""
}

func (m *SearchQueryInfo) GetRaw() string {
	if m != nil {
		return m.Raw
	}
	return ""
}

type MapFilterStats struct {
	TotalTerms           int32    `protobuf:"varint,1,opt,name=total_terms,json=totalTerms,proto3" json:"total_terms,omitempty"`
	Mapped               int32    `protobuf:"varint,2,opt,name=mapped,proto3" json:"mapped,omitempty"`
	Failed               int32    `protobuf:"varint,3,opt,name=failed,proto3" json:"failed,omitempty"`
	TotalTargets         int32    `protobuf:"varint,4,opt,name=total_targets,json=totalTargets,proto3" json:"total_targets,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MapFilterStats) Reset()         { *m = MapFilterStats{} }
func (m *MapFilterStats) String() string { return proto.CompactTextString(m) }
func (*MapFilterStats) ProtoMessage()    {}
func (*MapFilterStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{30}
}

func (m *MapFilterStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MapFilterStats.Unmarshal(m, b)
}
func (m *MapFilterStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MapFilterStats.Marshal(b, m, deterministic)
}
func (m *MapFilterStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MapFilterStats.Merge(m, src)
}
func (m *MapFilterStats) XXX_Size() int {
	return xxx_messageInfo_MapFilterStats.Size(m)
}
func (m *MapFilterStats) XXX_DiscardUnknown() {
	xxx_messageInfo_MapFilterStats.DiscardUnknown(m)
}

var xxx_messageInfo_MapFilterStats proto.InternalMessageInfo

func (m *MapFilterStats) GetTotalTerms() int32 {
	if m != nil {
		return m.TotalTerms
	}
	return 0
}

func (m *MapFilterStats) GetMapped() int32 {
	if m != nil {
		return m.Mapped
	}
	return 0
}

func (m *MapFilterStats) GetFailed() int32 {
	if m != nil {
		return m.Failed
	}
	return 0
}

func (m *MapFilterStats) GetTotalTargets() int32 {
	if m != nil {
		return m.TotalTargets
	}
	return 0
}

type SearchStats struct {
	TotalResults         int32            `protobuf:"varint,1,opt,name=total_results,json=totalResults,proto3" json:"total_results,omitempty"`
	Returned             int32            `protobuf:"varint,2,opt,name=returned,proto3" json:"returned,omitempty"`
	ByDataset            map[string]int32 `protobuf:"bytes,3,rep,name=by_dataset,json=byDataset,proto3" json:"by_dataset,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SearchStats) Reset()         { *m = SearchStats{} }
func (m *SearchStats) String() string { return proto.CompactTextString(m) }
func (*SearchStats) ProtoMessage()    {}
func (*SearchStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{31}
}

func (m *SearchStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchStats.Unmarshal(m, b)
}
func (m *SearchStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchStats.Marshal(b, m, deterministic)
}
func (m *SearchStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchStats.Merge(m, src)
}
func (m *SearchStats) XXX_Size() int {
	return xxx_messageInfo_SearchStats.Size(m)
}
func (m *SearchStats) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchStats.DiscardUnknown(m)
}

var xxx_messageInfo_SearchStats proto.InternalMessageInfo

func (m *SearchStats) GetTotalResults() int32 {
	if m != nil {
		return m.TotalResults
	}
	return 0
}

func (m *SearchStats) GetReturned() int32 {
	if m != nil {
		return m.Returned
	}
	return 0
}

func (m *SearchStats) GetByDataset() map[string]int32 {
	if m != nil {
		return m.ByDataset
	}
	return nil
}

type PaginationInfo struct {
	Page                 int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	HasNext              bool     `protobuf:"varint,2,opt,name=has_next,json=hasNext,proto3" json:"has_next,omitempty"`
	NextToken            string   `protobuf:"bytes,3,opt,name=next_token,json=nextToken,proto3" json:"next_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaginationInfo) Reset()         { *m = PaginationInfo{} }
func (m *PaginationInfo) String() string { return proto.CompactTextString(m) }
func (*PaginationInfo) ProtoMessage()    {}
func (*PaginationInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{32}
}

func (m *PaginationInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaginationInfo.Unmarshal(m, b)
}
func (m *PaginationInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaginationInfo.Marshal(b, m, deterministic)
}
func (m *PaginationInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaginationInfo.Merge(m, src)
}
func (m *PaginationInfo) XXX_Size() int {
	return xxx_messageInfo_PaginationInfo.Size(m)
}
func (m *PaginationInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PaginationInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PaginationInfo proto.InternalMessageInfo

func (m *PaginationInfo) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *PaginationInfo) GetHasNext() bool {
	if m != nil {
		return m.HasNext
	}
	return false
}

func (m *PaginationInfo) GetNextToken() string {
	if m != nil {
		return m.NextToken
	}
	return ""
}

func init() {
	proto.RegisterType((*SearchRequest)(nil), "pbuf.SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "pbuf.SearchResponse")
	proto.RegisterType((*MappingRequest)(nil), "pbuf.MappingRequest")
	proto.RegisterType((*MappingResponse)(nil), "pbuf.MappingResponse")
	proto.RegisterType((*EntryRequest)(nil), "pbuf.EntryRequest")
	proto.RegisterType((*EntryResponse)(nil), "pbuf.EntryResponse")
	proto.RegisterType((*PageRequest)(nil), "pbuf.PageRequest")
	proto.RegisterType((*PageResponse)(nil), "pbuf.PageResponse")
	proto.RegisterType((*FilterRequest)(nil), "pbuf.FilterRequest")
	proto.RegisterType((*FilterResponse)(nil), "pbuf.FilterResponse")
	proto.RegisterType((*MetaRequest)(nil), "pbuf.MetaRequest")
	proto.RegisterType((*MetaResponse)(nil), "pbuf.MetaResponse")
	proto.RegisterMapType((map[string]*MetaKeyValue)(nil), "pbuf.MetaResponse.ResultsEntry")
	proto.RegisterType((*MetaKeyValue)(nil), "pbuf.MetaKeyValue")
	proto.RegisterMapType((map[string]string)(nil), "pbuf.MetaKeyValue.KeyvaluesEntry")
	proto.RegisterType((*ListGenomesRequest)(nil), "pbuf.ListGenomesRequest")
	proto.RegisterType((*ListGenomesResponse)(nil), "pbuf.ListGenomesResponse")
	proto.RegisterType((*Result)(nil), "pbuf.Result")
	proto.RegisterType((*MapFilterResult)(nil), "pbuf.MapFilterResult")
	proto.RegisterType((*MapFilter)(nil), "pbuf.MapFilter")
	proto.RegisterType((*Xref)(nil), "pbuf.Xref")
	proto.RegisterMapType((map[uint32]*PageInfo)(nil), "pbuf.Xref.DatasetPagesEntry")
	proto.RegisterType((*PageInfo)(nil), "pbuf.PageInfo")
	proto.RegisterType((*XrefEntry)(nil), "pbuf.XrefEntry")
	proto.RegisterType((*XrefDomainCount)(nil), "pbuf.XrefDomainCount")
	proto.RegisterType((*Alias)(nil), "pbuf.Alias")
	proto.RegisterType((*MapFilterResultLite)(nil), "pbuf.MapFilterResultLite")
	proto.RegisterType((*MapFilterLite)(nil), "pbuf.MapFilterLite")
	proto.RegisterType((*LiteEntry)(nil), "pbuf.LiteEntry")
	proto.RegisterType((*ResultLite)(nil), "pbuf.ResultLite")
	proto.RegisterType((*SearchResultLite)(nil), "pbuf.SearchResultLite")
	proto.RegisterType((*MapFilterQueryInfo)(nil), "pbuf.MapFilterQueryInfo")
	proto.RegisterType((*SearchQueryInfo)(nil), "pbuf.SearchQueryInfo")
	proto.RegisterType((*MapFilterStats)(nil), "pbuf.MapFilterStats")
	proto.RegisterType((*SearchStats)(nil), "pbuf.SearchStats")
	proto.RegisterMapType((map[string]int32)(nil), "pbuf.SearchStats.ByDatasetEntry")
	proto.RegisterType((*PaginationInfo)(nil), "pbuf.PaginationInfo")
}

func init() { proto.RegisterFile("app.proto", fileDescriptor_e0f9056a14b86d47) }

var fileDescriptor_e0f9056a14b86d47 = []byte{
	// 2296 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x59, 0x5b, 0x73, 0x1b, 0x49,
	0x15, 0xde, 0xd1, 0xcd, 0xd2, 0xd1, 0xc5, 0x49, 0xdb, 0x71, 0x3a, 0xda, 0x4b, 0x9c, 0xd9, 0xb0,
	0x71, 0x36, 0x1b, 0x27, 0xd8, 0x4b, 0x20, 0x5b, 0xa1, 0x96, 0x38, 0xf7, 0xda, 0x24, 0x6b, 0xc6,
	0x59, 0x8a, 0x27, 0x4c, 0x4b, 0xd3, 0x92, 0x1a, 0x8f, 0x66, 0x26, 0xd3, 0xad, 0xd8, 0x82, 0x2a,
	0x8a, 0x07, 0x0a, 0x78, 0xa1, 0x78, 0xe6, 0x17, 0xc0, 0x03, 0x7f, 0x85, 0xbf, 0xc0, 0x6f, 0xe0,
	0x27, 0x50, 0x7d, 0x9b, 0xe9, 0x91, 0x9c, 0xdd, 0x64, 0xc3, 0xdb, 0xf4, 0x39, 0x5f, 0x9f, 0x3e,
	0x7d, 0x6e, 0x3a, 0x7d, 0x04, 0x2d, 0x92, 0xa6, 0xdb, 0x69, 0x96, 0x88, 0x04, 0xd5, 0xd2, 0xc1,
	0x6c, 0xd4, 0x07, 0x22, 0x44, 0xa6, 0x29, 0xfe, 0x3f, 0x3c, 0xe8, 0x1e, 0x50, 0x92, 0x0d, 0x27,
	0x01, 0x7d, 0x39, 0xa3, 0x5c, 0xa0, 0x75, 0xa8, 0x0b, 0x9a, 0x4d, 0x39, 0xf6, 0x36, 0xab, 0x5b,
	0xad, 0x40, 0x2f, 0x10, 0x86, 0x95, 0x90, 0x08, 0xc2, 0xa9, 0xc0, 0x95, 0x4d, 0x6f, 0xab, 0x15,
	0xd8, 0x25, 0x42, 0x50, 0x4b, 0xc9, 0x98, 0xe2, 0xaa, 0x22, 0xab, 0x6f, 0x29, 0xe3, 0xe5, 0x8c,
	0x66, 0x73, 0x5c, 0x53, 0x44, 0xbd, 0x40, 0x1b, 0xd0, 0x08, 0xa9, 0x20, 0x2c, 0xc2, 0xf5, 0x4d,
	0x6f, 0xab, 0x19, 0x98, 0x15, 0x3a, 0x03, 0xd5, 0x59, 0x16, 0xe1, 0x86, 0x22, 0xca, 0x4f, 0x29,
	0x73, 0x9a, 0x84, 0x14, 0xaf, 0x68, 0x99, 0xf2, 0xdb, 0x9f, 0x42, 0xcf, 0x2a, 0xca, 0xd3, 0x24,
	0xe6, 0x14, 0x7d, 0x02, 0x2b, 0x19, 0xe5, 0xb3, 0x48, 0x48, 0x5d, 0xbd, 0xad, 0xf6, 0x4e, 0x67,
	0x5b, 0xde, 0x6f, 0x3b, 0x50, 0xc4, 0xc0, 0x32, 0xd1, 0x2e, 0x74, 0xcc, 0xe7, 0x61, 0xc4, 0x04,
	0x55, 0x17, 0x68, 0xef, 0x9c, 0x71, 0xc1, 0x4f, 0x99, 0xa0, 0x41, 0xdb, 0xa0, 0xe4, 0xc2, 0xff,
	0x3d, 0xf4, 0x9e, 0x91, 0x34, 0x65, 0xf1, 0xf8, 0xfb, 0x1a, 0x26, 0x37, 0x42, 0xd5, 0x35, 0x82,
	0x35, 0x57, 0xcd, 0x31, 0x97, 0xbd, 0x6e, 0xdd, 0xb9, 0xee, 0x1f, 0x3c, 0x58, 0xcd, 0x15, 0x30,
	0x17, 0xbe, 0xb1, 0x78, 0xe1, 0x73, 0xfa, 0x0e, 0xcf, 0x48, 0xfa, 0x90, 0x45, 0x82, 0x66, 0x8b,
	0x37, 0xbf, 0x73, 0xea, 0xcd, 0x2f, 0x9c, 0xba, 0x6b, 0xd9, 0x04, 0x8f, 0xa1, 0xf3, 0x20, 0x16,
	0xd9, 0xdc, 0x1a, 0xe0, 0x23, 0x00, 0x16, 0xd2, 0x58, 0xb0, 0x11, 0xa3, 0x99, 0xd2, 0xa0, 0x15,
	0x38, 0x94, 0xd7, 0x9b, 0xc2, 0xdf, 0x85, 0xae, 0x91, 0x64, 0x6e, 0xe2, 0x43, 0x43, 0x9f, 0x64,
	0x2e, 0x02, 0x5a, 0xa5, 0x5f, 0x66, 0x74, 0x14, 0x18, 0x8e, 0xff, 0x12, 0xda, 0xfb, 0x64, 0x4c,
	0xdf, 0xf9, 0xf4, 0x52, 0x84, 0xd6, 0x8b, 0x08, 0x15, 0x89, 0x20, 0x91, 0xf2, 0x43, 0x3d, 0xd0,
	0x0b, 0xff, 0x73, 0xe8, 0xe8, 0x23, 0x8d, 0x9a, 0x97, 0x17, 0xd4, 0x2c, 0x07, 0x98, 0x55, 0xf4,
	0x18, 0xba, 0xd6, 0x90, 0xef, 0xaa, 0x2a, 0x86, 0x95, 0x91, 0x12, 0xc5, 0x71, 0x55, 0x45, 0x99,
	0x5d, 0x96, 0xe2, 0xc6, 0x5c, 0xc2, 0xbf, 0x05, 0xbd, 0xdc, 0x83, 0x6f, 0xa3, 0x70, 0x17, 0xda,
	0xcf, 0xa8, 0x20, 0x46, 0x5d, 0xff, 0xef, 0x1e, 0x74, 0xf4, 0xda, 0x48, 0xb9, 0xed, 0xc6, 0x59,
	0x75, 0xab, 0xbd, 0x73, 0xd1, 0x44, 0x8c, 0x03, 0x32, 0x32, 0xb9, 0xf6, 0xab, 0xc5, 0xf7, 0x9f,
	0x43, 0xc7, 0x65, 0xc8, 0xdc, 0x3e, 0xa2, 0x73, 0x63, 0x03, 0xf9, 0x89, 0xb6, 0xa0, 0xfe, 0x8a,
	0x44, 0x33, 0x1b, 0x8c, 0xa8, 0x10, 0xfd, 0x15, 0x9d, 0xff, 0x42, 0x72, 0x02, 0x0d, 0xf8, 0xa2,
	0xf2, 0x13, 0xcf, 0xff, 0xab, 0xd1, 0xcd, 0xf2, 0xd0, 0x97, 0xd0, 0x3a, 0xa2, 0x73, 0x05, 0xb0,
	0xda, 0x5d, 0x5a, 0x16, 0xb1, 0xfd, 0x95, 0xc5, 0x68, 0xfd, 0x8a, 0x3d, 0xfd, 0x3b, 0xd0, 0x2b,
	0x33, 0x4f, 0xd1, 0x71, 0xdd, 0xd5, 0xb1, 0xe5, 0xea, 0xb3, 0x05, 0xe8, 0x29, 0xe3, 0xe2, 0x11,
	0x8d, 0x93, 0x29, 0xe5, 0xd6, 0xe1, 0x08, 0x6a, 0x62, 0x9e, 0x52, 0x23, 0x42, 0x7d, 0xfb, 0x37,
	0x60, 0xad, 0x84, 0x34, 0xb6, 0xc5, 0xe5, 0x1c, 0x6e, 0xe5, 0xa6, 0xf3, 0xff, 0xeb, 0x41, 0x43,
	0xdb, 0x0e, 0x5d, 0x5e, 0x74, 0x80, 0x9b, 0x1f, 0x79, 0x76, 0xf7, 0xa1, 0x19, 0xd3, 0x13, 0xa1,
	0xc2, 0x42, 0x2b, 0x9a, 0xaf, 0xe5, 0x31, 0x53, 0xca, 0x79, 0x51, 0x98, 0xed, 0x12, 0x5d, 0x73,
	0x6b, 0x73, 0x5e, 0x42, 0x74, 0x69, 0xfd, 0xb9, 0x64, 0x3c, 0x89, 0x47, 0x89, 0xad, 0x56, 0x57,
	0xa0, 0xce, 0x05, 0x11, 0x5c, 0x95, 0xa6, 0xf6, 0xce, 0x59, 0x17, 0x7c, 0x20, 0x19, 0x81, 0xe6,
	0xa3, 0xcf, 0x01, 0x52, 0x32, 0x66, 0x31, 0x11, 0x2c, 0x89, 0x55, 0x29, 0x6f, 0xef, 0xac, 0x6b,
	0xf4, 0x7e, 0x4e, 0x57, 0x92, 0x1d, 0x9c, 0xff, 0xc7, 0x8a, 0x2a, 0x72, 0x6e, 0x19, 0x42, 0x57,
	0x17, 0xef, 0xbe, 0xba, 0x58, 0xae, 0xde, 0xd1, 0x00, 0xdb, 0x65, 0x03, 0xe0, 0x05, 0xf1, 0x4b,
	0x36, 0xf8, 0xb4, 0x6c, 0x83, 0xf5, 0x05, 0xfc, 0xff, 0xc1, 0x0c, 0xdf, 0x40, 0x2b, 0x17, 0x27,
	0x4b, 0x23, 0x4f, 0x66, 0xd9, 0x90, 0x9e, 0x56, 0x1a, 0x35, 0x47, 0xc6, 0x87, 0x20, 0xd9, 0x98,
	0x0a, 0x8e, 0x2b, 0xcb, 0xf1, 0x61, 0x58, 0xfe, 0xbf, 0x10, 0xd4, 0x24, 0xc5, 0xad, 0x37, 0x52,
	0x66, 0xb7, 0xa8, 0x37, 0x97, 0xa0, 0x63, 0x3e, 0x0f, 0x63, 0x32, 0xa5, 0xf8, 0xa2, 0x32, 0x55,
	0xdb, 0xd0, 0x9e, 0x93, 0x29, 0x45, 0xe7, 0x61, 0x85, 0xc9, 0x9f, 0x8f, 0xf8, 0x48, 0xd9, 0xb8,
	0x19, 0x34, 0x18, 0x7f, 0xca, 0xe2, 0xa3, 0x85, 0x2a, 0x57, 0x3d, 0xad, 0xca, 0x1d, 0xd1, 0xf9,
	0x71, 0x92, 0x85, 0xe6, 0xc7, 0xce, 0x2e, 0xd1, 0x06, 0xd4, 0xe9, 0x34, 0x15, 0x73, 0xdd, 0x07,
	0x3c, 0x7e, 0x2f, 0xd0, 0x4b, 0x74, 0x1d, 0x56, 0x66, 0x31, 0x93, 0x8d, 0x89, 0x31, 0x9d, 0x89,
	0xb7, 0x6f, 0x34, 0xf1, 0xae, 0x10, 0xd9, 0xe3, 0xf7, 0x02, 0x8b, 0x41, 0x37, 0xa1, 0x99, 0xc4,
	0x22, 0x89, 0x92, 0xf1, 0x5c, 0x75, 0x0a, 0x79, 0x31, 0xf9, 0xda, 0x50, 0xcd, 0x86, 0x1c, 0x85,
	0x2e, 0x43, 0x6d, 0x32, 0x8e, 0x87, 0xb8, 0xa9, 0xd0, 0x3d, 0x8d, 0x7e, 0x3c, 0x8e, 0x87, 0x06,
	0xa9, 0xb8, 0x52, 0x2e, 0x8b, 0x05, 0xcd, 0xd2, 0x2c, 0xc1, 0x2d, 0x57, 0xee, 0x13, 0x43, 0xb5,
	0x72, 0x2d, 0x4a, 0x2a, 0x4e, 0x63, 0x4e, 0xa7, 0x83, 0x08, 0x83, 0xab, 0xf8, 0x03, 0x4d, 0xb4,
	0x8a, 0x1b, 0x0c, 0xfa, 0x0c, 0x9a, 0x82, 0x9c, 0x24, 0x71, 0x32, 0x9d, 0xe3, 0xb6, 0xab, 0xca,
	0x0b, 0x72, 0x92, 0x0b, 0xb7, 0x08, 0xa5, 0xf4, 0x34, 0x1c, 0xe0, 0x4e, 0x49, 0xe9, 0x69, 0x38,
	0xc8, 0x95, 0x9e, 0x86, 0x03, 0x99, 0xa9, 0xc3, 0x09, 0x1d, 0x30, 0xbc, 0xa9, 0x60, 0x26, 0x69,
	0xee, 0x49, 0x92, 0xc1, 0x69, 0x3e, 0xba, 0x04, 0x55, 0x1a, 0x13, 0xdc, 0x55, 0xb0, 0xae, 0xd5,
	0x93, 0x18, 0x90, 0xe4, 0x49, 0x48, 0x1a, 0x0e, 0x70, 0xcf, 0x85, 0xec, 0xe7, 0xe7, 0x49, 0x9e,
	0xb4, 0x51, 0x98, 0xcd, 0xc6, 0x03, 0x12, 0x1f, 0xe1, 0x55, 0xd7, 0x46, 0xf7, 0x0d, 0xd5, 0x5e,
	0xc3, 0xa2, 0x94, 0xb7, 0xb2, 0x74, 0x42, 0x62, 0x2a, 0xf0, 0x99, 0x92, 0xb7, 0x0c, 0x35, 0xf7,
	0x96, 0x59, 0xa3, 0x1f, 0x43, 0x33, 0xa3, 0x64, 0x28, 0x92, 0x29, 0xc5, 0x67, 0xdd, 0xce, 0x25,
	0x30, 0xd4, 0x7d, 0x22, 0x26, 0xc7, 0x24, 0x77, 0xb3, 0x05, 0xa3, 0x4f, 0xa1, 0x31, 0x9c, 0x28,
	0x6f, 0x20, 0xb7, 0xd5, 0xbb, 0x37, 0x71, 0x9c, 0x61, 0x10, 0xe8, 0x16, 0x34, 0x67, 0x23, 0x4a,
	0xc4, 0x2c, 0xa3, 0x78, 0xcd, 0x2d, 0x08, 0x26, 0xe8, 0x1e, 0x6a, 0x9e, 0x3d, 0xc3, 0x62, 0xe5,
	0x19, 0x29, 0x11, 0x34, 0x16, 0xb8, 0xef, 0x9e, 0xb1, 0xaf, 0x68, 0xf6, 0x0c, 0x8d, 0x40, 0x7b,
	0xb0, 0x3a, 0x8c, 0x58, 0xcc, 0x86, 0x24, 0x3a, 0x14, 0x19, 0x23, 0x11, 0xc7, 0xef, 0xab, 0x4d,
	0xe7, 0x8d, 0x62, 0x86, 0xf9, 0x42, 0xf2, 0xcc, 0xde, 0xde, 0xd0, 0x25, 0x72, 0xb4, 0x03, 0xc0,
	0x45, 0xc6, 0xe2, 0xb1, 0x6c, 0xde, 0xf1, 0x07, 0xee, 0x99, 0x07, 0x8a, 0x6e, 0xf6, 0x39, 0x28,
	0xb4, 0x0b, 0x2d, 0x12, 0xa5, 0x13, 0x32, 0x4a, 0xa2, 0x10, 0x7f, 0xa8, 0xb6, 0xac, 0xe9, 0x2d,
	0x77, 0x25, 0xf9, 0x61, 0x12, 0x85, 0x66, 0x57, 0x81, 0x43, 0xb7, 0x00, 0xb2, 0x98, 0x0c, 0x69,
	0x2c, 0x32, 0x12, 0xe1, 0x8f, 0xdc, 0x12, 0x16, 0xe4, 0x74, 0x7b, 0x58, 0x81, 0x94, 0x39, 0x20,
	0x55, 0x7e, 0x45, 0x32, 0x7c, 0xc9, 0xcd, 0x81, 0x7b, 0x9a, 0x68, 0x73, 0xc0, 0x60, 0xa4, 0x6e,
	0x11, 0x4b, 0x59, 0x38, 0x25, 0x29, 0xc7, 0xbe, 0xab, 0xdb, 0x53, 0x4b, 0xb6, 0xba, 0xe5, 0x38,
	0x74, 0x1b, 0xda, 0xfc, 0x98, 0x71, 0xae, 0x28, 0x1c, 0x7f, 0x5c, 0xfa, 0x05, 0x2b, 0x18, 0x66,
	0xa3, 0x8b, 0x95, 0x59, 0x34, 0x18, 0x53, 0x8a, 0x2f, 0xbb, 0x59, 0xb4, 0x37, 0xa6, 0xd6, 0xb3,
	0x8a, 0x2b, 0x51, 0xd9, 0x84, 0x12, 0xfc, 0x89, 0x8b, 0x0a, 0x26, 0xd4, 0xa6, 0x87, 0xe2, 0xca,
	0x2a, 0x3f, 0x3e, 0x26, 0xfc, 0x90, 0x8b, 0x59, 0x38, 0xc7, 0x57, 0x5c, 0xe5, 0x1f, 0x1d, 0x13,
	0x7e, 0x20, 0xc9, 0x56, 0xf9, 0xb1, 0x25, 0x48, 0xd9, 0x72, 0x81, 0xaf, 0xb9, 0xb2, 0x25, 0xde,
	0xca, 0x96, 0x5c, 0x19, 0x57, 0x2c, 0x16, 0x64, 0x28, 0xf0, 0x67, 0xae, 0x8f, 0x9f, 0x28, 0x9a,
	0x8d, 0x2b, 0x8d, 0x40, 0x4f, 0x01, 0xc9, 0x10, 0xa5, 0x2c, 0x3e, 0xe4, 0x6c, 0xca, 0x22, 0x92,
	0x31, 0x31, 0xc7, 0xd7, 0xd5, 0xbe, 0xf7, 0x4d, 0x3c, 0x6a, 0xfe, 0x41, 0xce, 0x36, 0x22, 0xce,
	0xa6, 0x8b, 0x0c, 0x99, 0xa0, 0x24, 0x16, 0x6c, 0x90, 0x84, 0x73, 0xbc, 0xed, 0x26, 0xe8, 0x5d,
	0x43, 0xb5, 0x39, 0x60, 0x51, 0xd2, 0xe5, 0xe9, 0x6c, 0x20, 0x13, 0x09, 0xdf, 0x70, 0x5d, 0xbe,
	0xaf, 0x89, 0xd6, 0xe5, 0x06, 0x83, 0x1e, 0xc2, 0x19, 0xf3, 0x79, 0x48, 0x86, 0x82, 0xbd, 0x92,
	0xca, 0xde, 0x74, 0xf3, 0xda, 0xee, 0x33, 0x4c, 0xb3, 0x7f, 0x35, 0x2d, 0x93, 0xd1, 0x4f, 0xa1,
	0x9b, 0xcb, 0xe1, 0x9c, 0xcc, 0xf1, 0x0f, 0x95, 0x90, 0x8d, 0xb2, 0x10, 0xc9, 0x31, 0x12, 0x3a,
	0xa9, 0x43, 0x93, 0x95, 0x32, 0x1c, 0xf0, 0x38, 0xc5, 0xbf, 0x73, 0x2b, 0xe5, 0x7d, 0x49, 0xb2,
	0x95, 0x52, 0xf1, 0xa5, 0xc3, 0xa6, 0x94, 0x4f, 0xf0, 0x8e, 0xeb, 0xb0, 0x67, 0x94, 0x4f, 0xac,
	0xc3, 0x24, 0x57, 0x3a, 0x4c, 0x66, 0x00, 0xfd, 0x2d, 0xfe, 0x91, 0xeb, 0xb0, 0x07, 0x8a, 0x66,
	0x1d, 0xa6, 0x11, 0x12, 0x9b, 0xd1, 0x11, 0xa7, 0x2f, 0xf1, 0xed, 0xf2, 0x1b, 0x74, 0x74, 0x40,
	0x5f, 0x5a, 0xac, 0x46, 0x48, 0x35, 0xc7, 0x34, 0x1e, 0x0e, 0xf1, 0x17, 0xae, 0x9a, 0x8f, 0x24,
	0xc9, 0xaa, 0xa9, 0xf8, 0xb2, 0x59, 0x1d, 0x26, 0xb3, 0x58, 0xe0, 0x75, 0xf5, 0xdb, 0xae, 0x17,
	0xb2, 0x8d, 0x92, 0x87, 0x32, 0xca, 0xf1, 0x39, 0xb7, 0x8d, 0x92, 0x0d, 0x81, 0xe9, 0xd9, 0x0d,
	0x1f, 0xdd, 0x81, 0x9e, 0x6d, 0x02, 0xd4, 0x5e, 0x8e, 0x37, 0xd4, 0x8e, 0x73, 0xc5, 0x8e, 0xfb,
	0xc9, 0x94, 0xb0, 0xf8, 0x9e, 0xe4, 0x06, 0x5d, 0x03, 0x56, 0x2b, 0x8e, 0x7e, 0x96, 0xb7, 0x10,
	0xf2, 0xe9, 0xc4, 0xf1, 0x79, 0xb5, 0xf7, 0x83, 0x62, 0xef, 0xf6, 0x7d, 0x87, 0xad, 0x8f, 0x2e,
	0xed, 0x90, 0x17, 0x48, 0xd5, 0x56, 0xac, 0x1f, 0xd6, 0x6a, 0x61, 0xa7, 0x02, 0x17, 0x74, 0x57,
	0x3e, 0xcb, 0xa2, 0xfe, 0xd7, 0x70, 0x76, 0x49, 0x94, 0xdb, 0xbc, 0x77, 0x75, 0xf3, 0x7e, 0xb9,
	0xfc, 0xc0, 0xe8, 0xe5, 0xed, 0x17, 0xd5, 0x5d, 0x5d, 0xde, 0xcc, 0xef, 0x75, 0x40, 0x8d, 0x42,
	0xd8, 0x60, 0x26, 0x28, 0xf7, 0x37, 0xa1, 0x69, 0x41, 0x85, 0x4a, 0x9e, 0xa3, 0x92, 0xff, 0x4f,
	0x0f, 0x5a, 0xb9, 0xfd, 0xde, 0xa2, 0xab, 0xaa, 0x2d, 0x77, 0x55, 0xe5, 0xe6, 0xa9, 0xb2, 0xd4,
	0x3c, 0xf5, 0xa1, 0x49, 0x5f, 0xc9, 0xf5, 0xd0, 0xf6, 0xaf, 0xf9, 0x1a, 0xf9, 0xf2, 0x55, 0x1f,
	0xa9, 0xd6, 0x91, 0x4f, 0x58, 0x6a, 0xc6, 0x06, 0x25, 0x9a, 0x7f, 0x17, 0x56, 0x17, 0xfc, 0xf6,
	0x2d, 0xfa, 0xe6, 0x11, 0x54, 0x71, 0x22, 0xc8, 0xbf, 0x0a, 0xf5, 0xbb, 0x11, 0x23, 0x1c, 0x6d,
	0x42, 0xbb, 0xd0, 0xcc, 0x9a, 0xc4, 0x25, 0xf9, 0x7f, 0xa9, 0xc0, 0xda, 0x29, 0xe3, 0x84, 0x7c,
	0xb0, 0xe1, 0x15, 0x83, 0x8d, 0xa2, 0xfd, 0xae, 0xbc, 0x59, 0xfb, 0x7d, 0x03, 0x9a, 0x53, 0x3d,
	0x07, 0xd1, 0x6f, 0xe2, 0xbc, 0xd4, 0xe6, 0x5b, 0xd4, 0xe4, 0x22, 0x07, 0x15, 0xfd, 0x7a, 0xed,
	0x6d, 0xfb, 0xf5, 0xfa, 0x9b, 0xf5, 0xeb, 0xd2, 0x39, 0xc7, 0x24, 0x8b, 0x95, 0x4a, 0x0d, 0x65,
	0x8d, 0x7c, 0xed, 0xff, 0xcd, 0x83, 0x6e, 0x49, 0x33, 0x69, 0x5d, 0x16, 0xa7, 0x33, 0x61, 0xac,
	0xa0, 0x17, 0xe8, 0x4a, 0xde, 0xe6, 0x57, 0xdc, 0xfc, 0x96, 0x3b, 0x74, 0x8e, 0xd8, 0x5e, 0xff,
	0x6a, 0xd1, 0xeb, 0x57, 0xdd, 0x44, 0x2e, 0x90, 0x96, 0x2f, 0x4f, 0xa2, 0x59, 0x96, 0x64, 0x76,
	0xec, 0xa6, 0x16, 0xfe, 0x7d, 0x68, 0xe5, 0x58, 0xd4, 0x01, 0x2f, 0x34, 0x8a, 0x78, 0x21, 0xea,
	0x41, 0x85, 0x85, 0x26, 0xfa, 0x2a, 0x2c, 0x44, 0x17, 0xa0, 0x39, 0x21, 0xfc, 0x50, 0xb5, 0x18,
	0x55, 0xd5, 0xec, 0xaf, 0x4c, 0xf4, 0xef, 0x93, 0xff, 0x1f, 0x0f, 0xe0, 0x3b, 0x3c, 0x7b, 0xad,
	0xec, 0xd9, 0x6f, 0x7f, 0x59, 0xde, 0x2c, 0x9e, 0x79, 0xfa, 0x5a, 0x1b, 0x2e, 0xdc, 0x19, 0x49,
	0xe5, 0xaf, 0xbd, 0x2b, 0x65, 0xbf, 0xbe, 0xe9, 0x5b, 0xf4, 0x0d, 0x9d, 0xea, 0xff, 0x06, 0xce,
	0x2c, 0x9e, 0xfd, 0xbd, 0xad, 0x85, 0x3e, 0x04, 0x38, 0xc9, 0xe8, 0x48, 0xd7, 0x53, 0xa5, 0x70,
	0x37, 0x68, 0x49, 0x8a, 0x4a, 0x45, 0x3f, 0x00, 0xb4, 0x1c, 0xf0, 0xaf, 0x19, 0x30, 0xca, 0xe4,
	0x9c, 0x10, 0x16, 0xdb, 0x59, 0x84, 0x5a, 0xc8, 0xb2, 0x97, 0x91, 0x63, 0x53, 0x1a, 0xe4, 0xa7,
	0xff, 0x6b, 0x58, 0x5d, 0x30, 0xf5, 0x6b, 0x04, 0xfe, 0xa0, 0x28, 0xf7, 0x7a, 0xb8, 0x64, 0x24,
	0xdb, 0xba, 0x6e, 0xde, 0xa1, 0xcb, 0x27, 0xfc, 0xc9, 0x53, 0x33, 0x51, 0x27, 0x8d, 0xd0, 0x45,
	0x68, 0xab, 0xc9, 0xd9, 0xa1, 0x3d, 0xc7, 0xdb, 0xaa, 0x07, 0xa0, 0x48, 0x2f, 0xd4, 0x61, 0x1b,
	0xd0, 0x90, 0x89, 0x49, 0xb5, 0xdd, 0xea, 0x81, 0x59, 0x49, 0xfa, 0x88, 0xb0, 0x88, 0x86, 0x66,
	0x2a, 0x67, 0x56, 0xe8, 0x63, 0xe8, 0x1a, 0x81, 0x26, 0xe6, 0xf5, 0xbc, 0xab, 0xa3, 0x45, 0x9a,
	0x87, 0xed, 0xbf, 0x3d, 0x68, 0x3b, 0x7e, 0x2f, 0x36, 0xb9, 0x93, 0x15, 0xbb, 0x29, 0x28, 0x86,
	0x05, 0x19, 0x15, 0xb3, 0x2c, 0xce, 0x75, 0xc9, 0xd7, 0xe8, 0x4b, 0x80, 0xc1, 0xfc, 0xd0, 0x56,
	0x47, 0x1d, 0x8f, 0x9b, 0x4b, 0xf1, 0xb5, 0xbd, 0x37, 0x37, 0xbf, 0x3f, 0x66, 0xa8, 0x34, 0xb0,
	0xeb, 0xfe, 0x1d, 0xe8, 0x95, 0x99, 0xdf, 0x35, 0x54, 0xaa, 0xbb, 0x43, 0xa5, 0x5f, 0x41, 0xaf,
	0x1c, 0x98, 0xf9, 0xb4, 0xcf, 0x73, 0x46, 0x96, 0x26, 0xdc, 0x62, 0x7a, 0x22, 0xcc, 0x4b, 0x5c,
	0x86, 0xdb, 0x73, 0x7a, 0x22, 0x64, 0xb8, 0x49, 0xf2, 0xa1, 0x48, 0x8e, 0x68, 0x6c, 0x5c, 0xd6,
	0x92, 0x94, 0x17, 0x92, 0xb0, 0xf3, 0xe7, 0x2a, 0xac, 0xee, 0xb1, 0x64, 0x20, 0x32, 0x4a, 0x0f,
	0x68, 0xf6, 0x8a, 0x0d, 0x29, 0xda, 0x85, 0x86, 0xbe, 0x1a, 0x5a, 0x2b, 0x27, 0x9e, 0x9a, 0x68,
	0xf5, 0xd7, 0x17, 0xb2, 0x51, 0x0f, 0xaf, 0x6e, 0xc1, 0x8a, 0x99, 0x49, 0xa3, 0xa2, 0xac, 0x3a,
	0x33, 0xf2, 0xfe, 0xb9, 0x05, 0xaa, 0xd9, 0x77, 0x13, 0xea, 0xda, 0x2a, 0xa8, 0x68, 0x8e, 0xec,
	0x58, 0xb9, 0xbf, 0x56, 0xa2, 0x99, 0x1d, 0xd7, 0xa1, 0x26, 0x7f, 0x8c, 0xd1, 0xd9, 0xe2, 0xd7,
	0xdb, 0xe2, 0x91, 0x4b, 0x32, 0xf0, 0x5d, 0x68, 0x98, 0xb0, 0x35, 0xd2, 0x4a, 0x03, 0x59, 0x7b,
	0x9b, 0x85, 0x61, 0xe9, 0x75, 0xa8, 0x3d, 0xa3, 0x82, 0xd8, 0x33, 0x9c, 0x91, 0x68, 0x1f, 0x2d,
	0x0f, 0x3c, 0xd1, 0x1e, 0xb4, 0x9d, 0x81, 0x1e, 0xc2, 0xb6, 0x0c, 0x2f, 0x4e, 0x03, 0xfb, 0x17,
	0x4e, 0xe1, 0x68, 0x19, 0x83, 0x86, 0xfa, 0xd7, 0x65, 0xf7, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x27, 0x05, 0xb8, 0x23, 0x94, 0x19, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BiobtreeServiceClient is the client API for BiobtreeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BiobtreeServiceClient interface {
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	Mapping(ctx context.Context, in *MappingRequest, opts ...grpc.CallOption) (*MappingResponse, error)
	Entry(ctx context.Context, in *EntryRequest, opts ...grpc.CallOption) (*EntryResponse, error)
	Page(ctx context.Context, in *PageRequest, opts ...grpc.CallOption) (*PageResponse, error)
	Filter(ctx context.Context, in *FilterRequest, opts ...grpc.CallOption) (*FilterResponse, error)
	Meta(ctx context.Context, in *MetaRequest, opts ...grpc.CallOption) (*MetaResponse, error)
	ListGenomes(ctx context.Context, in *ListGenomesRequest, opts ...grpc.CallOption) (*ListGenomesResponse, error)
}

type biobtreeServiceClient struct {
	cc *grpc.ClientConn
}

func NewBiobtreeServiceClient(cc *grpc.ClientConn) BiobtreeServiceClient {
	return &biobtreeServiceClient{cc}
}

func (c *biobtreeServiceClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, "/pbuf.BiobtreeService/Search", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *biobtreeServiceClient) Mapping(ctx context.Context, in *MappingRequest, opts ...grpc.CallOption) (*MappingResponse, error) {
	out := new(MappingResponse)
	err := c.cc.Invoke(ctx, "/pbuf.BiobtreeService/Mapping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *biobtreeServiceClient) Entry(ctx context.Context, in *EntryRequest, opts ...grpc.CallOption) (*EntryResponse, error) {
	out := new(EntryResponse)
	err := c.cc.Invoke(ctx, "/pbuf.BiobtreeService/Entry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *biobtreeServiceClient) Page(ctx context.Context, in *PageRequest, opts ...grpc.CallOption) (*PageResponse, error) {
	out := new(PageResponse)
	err := c.cc.Invoke(ctx, "/pbuf.BiobtreeService/Page", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *biobtreeServiceClient) Filter(ctx context.Context, in *FilterRequest, opts ...grpc.CallOption) (*FilterResponse, error) {
	out := new(FilterResponse)
	err := c.cc.Invoke(ctx, "/pbuf.BiobtreeService/Filter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *biobtreeServiceClient) Meta(ctx context.Context, in *MetaRequest, opts ...grpc.CallOption) (*MetaResponse, error) {
	out := new(MetaResponse)
	err := c.cc.Invoke(ctx, "/pbuf.BiobtreeService/Meta", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *biobtreeServiceClient) ListGenomes(ctx context.Context, in *ListGenomesRequest, opts ...grpc.CallOption) (*ListGenomesResponse, error) {
	out := new(ListGenomesResponse)
	err := c.cc.Invoke(ctx, "/pbuf.BiobtreeService/ListGenomes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BiobtreeServiceServer is the server API for BiobtreeService service.
type BiobtreeServiceServer interface {
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	Mapping(context.Context, *MappingRequest) (*MappingResponse, error)
	Entry(context.Context, *EntryRequest) (*EntryResponse, error)
	Page(context.Context, *PageRequest) (*PageResponse, error)
	Filter(context.Context, *FilterRequest) (*FilterResponse, error)
	Meta(context.Context, *MetaRequest) (*MetaResponse, error)
	ListGenomes(context.Context, *ListGenomesRequest) (*ListGenomesResponse, error)
}

// UnimplementedBiobtreeServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBiobtreeServiceServer struct {
}

func (*UnimplementedBiobtreeServiceServer) Search(ctx context.Context, req *SearchRequest) (*SearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (*UnimplementedBiobtreeServiceServer) Mapping(ctx context.Context, req *MappingRequest) (*MappingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Mapping not implemented")
}
func (*UnimplementedBiobtreeServiceServer) Entry(ctx context.Context, req *EntryRequest) (*EntryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Entry not implemented")
}
func (*UnimplementedBiobtreeServiceServer) Page(ctx context.Context, req *PageRequest) (*PageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Page not implemented")
}
func (*UnimplementedBiobtreeServiceServer) Filter(ctx context.Context, req *FilterRequest) (*FilterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Filter not implemented")
}
func (*UnimplementedBiobtreeServiceServer) Meta(ctx context.Context, req *MetaRequest) (*MetaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Meta not implemented")
}
func (*UnimplementedBiobtreeServiceServer) ListGenomes(ctx context.Context, req *ListGenomesRequest) (*ListGenomesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListGenomes not implemented")
}

func RegisterBiobtreeServiceServer(s *grpc.Server, srv BiobtreeServiceServer) {
	s.RegisterService(&_BiobtreeService_serviceDesc, srv)
}

func _BiobtreeService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BiobtreeServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbuf.BiobtreeService/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BiobtreeServiceServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BiobtreeService_Mapping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MappingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BiobtreeServiceServer).Mapping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbuf.BiobtreeService/Mapping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BiobtreeServiceServer).Mapping(ctx, req.(*MappingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BiobtreeService_Entry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BiobtreeServiceServer).Entry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbuf.BiobtreeService/Entry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BiobtreeServiceServer).Entry(ctx, req.(*EntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BiobtreeService_Page_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BiobtreeServiceServer).Page(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbuf.BiobtreeService/Page",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BiobtreeServiceServer).Page(ctx, req.(*PageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BiobtreeService_Filter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FilterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BiobtreeServiceServer).Filter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbuf.BiobtreeService/Filter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BiobtreeServiceServer).Filter(ctx, req.(*FilterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BiobtreeService_Meta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BiobtreeServiceServer).Meta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbuf.BiobtreeService/Meta",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BiobtreeServiceServer).Meta(ctx, req.(*MetaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BiobtreeService_ListGenomes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGenomesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BiobtreeServiceServer).ListGenomes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbuf.BiobtreeService/ListGenomes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BiobtreeServiceServer).ListGenomes(ctx, req.(*ListGenomesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BiobtreeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pbuf.BiobtreeService",
	HandlerType: (*BiobtreeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _BiobtreeService_Search_Handler,
		},
		{
			MethodName: "Mapping",
			Handler:    _BiobtreeService_Mapping_Handler,
		},
		{
			MethodName: "Entry",
			Handler:    _BiobtreeService_Entry_Handler,
		},
		{
			MethodName: "Page",
			Handler:    _BiobtreeService_Page_Handler,
		},
		{
			MethodName: "Filter",
			Handler:    _BiobtreeService_Filter_Handler,
		},
		{
			MethodName: "Meta",
			Handler:    _BiobtreeService_Meta_Handler,
		},
		{
			MethodName: "ListGenomes",
			Handler:    _BiobtreeService_ListGenomes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app.proto",
}
