// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pbuf.proto

package pbuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Xref struct {
	// Types that are valid to be assigned to Attributes:
	//	*Xref_Uattr
	//	*Xref_Gattr
	Attributes           isXref_Attributes `protobuf_oneof:"attributes"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Xref) Reset()         { *m = Xref{} }
func (m *Xref) String() string { return proto.CompactTextString(m) }
func (*Xref) ProtoMessage()    {}
func (*Xref) Descriptor() ([]byte, []int) {
	return fileDescriptor_340fcfad62fd30ca, []int{0}
}

func (m *Xref) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Xref.Unmarshal(m, b)
}
func (m *Xref) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Xref.Marshal(b, m, deterministic)
}
func (m *Xref) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Xref.Merge(m, src)
}
func (m *Xref) XXX_Size() int {
	return xxx_messageInfo_Xref.Size(m)
}
func (m *Xref) XXX_DiscardUnknown() {
	xxx_messageInfo_Xref.DiscardUnknown(m)
}

var xxx_messageInfo_Xref proto.InternalMessageInfo

type isXref_Attributes interface {
	isXref_Attributes()
}

type Xref_Uattr struct {
	Uattr *UniAttr `protobuf:"bytes,1,opt,name=uattr,proto3,oneof"`
}

type Xref_Gattr struct {
	Gattr *GoAttr `protobuf:"bytes,2,opt,name=gattr,proto3,oneof"`
}

func (*Xref_Uattr) isXref_Attributes() {}

func (*Xref_Gattr) isXref_Attributes() {}

func (m *Xref) GetAttributes() isXref_Attributes {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *Xref) GetUattr() *UniAttr {
	if x, ok := m.GetAttributes().(*Xref_Uattr); ok {
		return x.Uattr
	}
	return nil
}

func (m *Xref) GetGattr() *GoAttr {
	if x, ok := m.GetAttributes().(*Xref_Gattr); ok {
		return x.Gattr
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Xref) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Xref_Uattr)(nil),
		(*Xref_Gattr)(nil),
	}
}

type GoAttr struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Label                string   `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Synonyms             []string `protobuf:"bytes,3,rep,name=synonyms,proto3" json:"synonyms,omitempty"`
	LocusGroup           []string `protobuf:"bytes,4,rep,name=locus_group,json=locusGroup,proto3" json:"locus_group,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GoAttr) Reset()         { *m = GoAttr{} }
func (m *GoAttr) String() string { return proto.CompactTextString(m) }
func (*GoAttr) ProtoMessage()    {}
func (*GoAttr) Descriptor() ([]byte, []int) {
	return fileDescriptor_340fcfad62fd30ca, []int{1}
}

func (m *GoAttr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoAttr.Unmarshal(m, b)
}
func (m *GoAttr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoAttr.Marshal(b, m, deterministic)
}
func (m *GoAttr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoAttr.Merge(m, src)
}
func (m *GoAttr) XXX_Size() int {
	return xxx_messageInfo_GoAttr.Size(m)
}
func (m *GoAttr) XXX_DiscardUnknown() {
	xxx_messageInfo_GoAttr.DiscardUnknown(m)
}

var xxx_messageInfo_GoAttr proto.InternalMessageInfo

func (m *GoAttr) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *GoAttr) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *GoAttr) GetSynonyms() []string {
	if m != nil {
		return m.Synonyms
	}
	return nil
}

func (m *GoAttr) GetLocusGroup() []string {
	if m != nil {
		return m.LocusGroup
	}
	return nil
}

type UniAttr struct {
	Accessions           []string `protobuf:"bytes,1,rep,name=accessions,proto3" json:"accessions,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Start                int32    `protobuf:"varint,3,opt,name=start,proto3" json:"start,omitempty"`
	End                  int32    `protobuf:"varint,4,opt,name=end,proto3" json:"end,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UniAttr) Reset()         { *m = UniAttr{} }
func (m *UniAttr) String() string { return proto.CompactTextString(m) }
func (*UniAttr) ProtoMessage()    {}
func (*UniAttr) Descriptor() ([]byte, []int) {
	return fileDescriptor_340fcfad62fd30ca, []int{2}
}

func (m *UniAttr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UniAttr.Unmarshal(m, b)
}
func (m *UniAttr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UniAttr.Marshal(b, m, deterministic)
}
func (m *UniAttr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UniAttr.Merge(m, src)
}
func (m *UniAttr) XXX_Size() int {
	return xxx_messageInfo_UniAttr.Size(m)
}
func (m *UniAttr) XXX_DiscardUnknown() {
	xxx_messageInfo_UniAttr.DiscardUnknown(m)
}

var xxx_messageInfo_UniAttr proto.InternalMessageInfo

func (m *UniAttr) GetAccessions() []string {
	if m != nil {
		return m.Accessions
	}
	return nil
}

func (m *UniAttr) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UniAttr) GetStart() int32 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *UniAttr) GetEnd() int32 {
	if m != nil {
		return m.End
	}
	return 0
}

func init() {
	proto.RegisterType((*Xref)(nil), "pbuf.Xref")
	proto.RegisterType((*GoAttr)(nil), "pbuf.GoAttr")
	proto.RegisterType((*UniAttr)(nil), "pbuf.UniAttr")
}

func init() { proto.RegisterFile("pbuf.proto", fileDescriptor_340fcfad62fd30ca) }

var fileDescriptor_340fcfad62fd30ca = []byte{
	// 243 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x90, 0xcf, 0x4a, 0xc4, 0x30,
	0x10, 0xc6, 0xad, 0x4d, 0x57, 0x3b, 0xbb, 0x82, 0x0c, 0x1e, 0x82, 0x07, 0x2d, 0x45, 0xa1, 0xa7,
	0x3d, 0xe8, 0x13, 0xe8, 0x65, 0x3d, 0x07, 0x04, 0x6f, 0x92, 0xd6, 0xec, 0x52, 0xe8, 0x26, 0x25,
	0x99, 0x1c, 0xfa, 0xf6, 0x92, 0xc9, 0xea, 0x9e, 0xfa, 0xfd, 0xf9, 0xd1, 0xf9, 0x08, 0xc0, 0xdc,
	0xc7, 0xfd, 0x76, 0xf6, 0x8e, 0x1c, 0x8a, 0xa4, 0x5b, 0x0d, 0xe2, 0xcb, 0x9b, 0x3d, 0x3e, 0x43,
	0x15, 0x35, 0x91, 0x97, 0x45, 0x53, 0x74, 0xeb, 0x97, 0x9b, 0x2d, 0x93, 0x9f, 0x76, 0x7c, 0x23,
	0xf2, 0x1f, 0x17, 0x2a, 0xb7, 0xf8, 0x04, 0xd5, 0x81, 0xb1, 0x4b, 0xc6, 0x36, 0x19, 0xdb, 0xb9,
	0x3f, 0x8a, 0xcb, 0xf7, 0x0d, 0x40, 0xfa, 0x8e, 0x7d, 0x24, 0x13, 0x5a, 0x07, 0xab, 0x0c, 0x20,
	0x82, 0xa0, 0x65, 0x36, 0x7c, 0xa3, 0x56, 0xac, 0xf1, 0x0e, 0xaa, 0x49, 0xf7, 0x66, 0xe2, 0x3f,
	0xd6, 0x2a, 0x1b, 0xbc, 0x87, 0xeb, 0xb0, 0x58, 0x67, 0x97, 0x63, 0x90, 0x65, 0x53, 0x76, 0xb5,
	0xfa, 0xf7, 0xf8, 0x08, 0xeb, 0xc9, 0x0d, 0x31, 0x7c, 0x1f, 0xbc, 0x8b, 0xb3, 0x14, 0x5c, 0x03,
	0x47, 0xbb, 0x94, 0xb4, 0x06, 0xae, 0x4e, 0xc3, 0xf1, 0x01, 0x40, 0x0f, 0x83, 0x09, 0x61, 0x74,
	0x36, 0xc8, 0x22, 0xa3, 0xe7, 0x24, 0x2d, 0xb2, 0xfa, 0x68, 0x4e, 0xc7, 0x59, 0xa7, 0x45, 0x81,
	0xb4, 0x27, 0x59, 0x36, 0x45, 0x57, 0xa9, 0x6c, 0xf0, 0x16, 0x4a, 0x63, 0x7f, 0xa4, 0xe0, 0x2c,
	0xc9, 0x7e, 0xc5, 0xef, 0xf8, 0xfa, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xbd, 0xd3, 0x23, 0x4a, 0x55,
	0x01, 0x00, 0x00,
}
